### PR TITLE
[gpu] clean up and fix 2.0 clusters w/ master-only GPUs

### PR DESCRIPTION
**Pull request by medb**
Changes:
- configure YARN NodeManager to use GPUs only if GPUs are attached to the node (fixes 2.0 clusters creation with GPUs attached only to master nodes)
- install NCCL only if cuDNN installed
- code clean up
- run tests for single-node clusters

### CODE REVIEW

**Comment by bradmiro** [comment]
@mengdong Does XGBoost not need nccl?

**Comment by bradmiro** [comment]
> @mengdong Does XGBoost not need nccl?

Nevermind, I think this is fine. LGTM

**Review by animeshnandanwar — APPROVED** [review]
LGTM

**Pull request merged**
