### PR TITLE
update xgboost 171 to 176

### PR DESCRIPTION
**Pull request by nvliyuan**
Signed-off-by: liyuan <yuali@nvidia.com>
update xgboost version from 171 to 176 due to https://github.com/dmlc/xgboost/issues/9374

### CODE REVIEW

**Comment by nvliyuan** [comment]
@jayadeep-jayaraman @cjac could you help build?
FYI @viadea

**Comment by nvliyuan** [comment]
Hi @cjac could you help check why the build failed?

**Comment by cjac** [comment]
you might find better results in the long term if you change that a100 to a t4

**Comment by nvliyuan** [comment]
The [MIG Test](https://docs.nvidia.com/datacenter/tesla/mig-user-guide/#running-with-mig) needs specific A100 or A30 GPUs, and A30 is not supported according to [this doc](https://cloud.google.com/dataproc/docs/concepts/compute/gpus#types_of_gpus), seems we can only attach A100.
Is it possible to add more A100?

**Comment by cjac** [comment]
I think if we add more, they will be consumed.  The demand is super high.  I know we have done queue software for TPUs, but nothing for NVIDIA hardware yet.  I'll just keep retrying.

**Comment by viadea** [comment]
@cjac  @nvliyuan  what is the status of this PR?thx

@SurajAralihalli  FYI

**Comment by cjac** [comment]
@jayadeep-jayaraman - can you look at this with me next week?

**Comment by nvliyuan** [comment]
@jayadeep-jayaraman  @cjac I disabled MIG-related tests due to the lack of A100 GPU temporarily, we can merge the pr first .
CC @viadea @SurajAralihalli

**Comment by viadea** [comment]
I am fine. 

@SurajAralihalli  FYI

**Comment by nvliyuan** [comment]
Seems the checks have passed after we disable MIG tests, could you help merge? @cjac

**Comment by nvliyuan** [comment]
Hi @viadea, could you please help review the pr?

**Comment by viadea** [comment]
> Hi @viadea, could you please help review the pr?

LGTM

**Review by viadea — APPROVED** [review]

**Review by jayadeep-jayaraman — APPROVED** [review]

**Pull request merged**
