### PR TITLE
[kafka] Removed duplicate tests and upgraded jfrog dependency

### PR DESCRIPTION
**Pull request by prince-cs**

### CODE REVIEW

**Comment by prince-cs** [comment]
passing build with the latest changes related to kafka

https://pantheon.corp.google.com/cloud-build/builds;region=global/b0a0258f-f1c9-499f-babf-02404f9e47fa?inv=1&invt=AbabyQ&mods=dataproc_env_image_prod&project=cloud-dataproc-ci

**Review by kuldeepkk-dev — APPROVED** [review]
LGTM. 

Discussed with Prince on compatibility of this change with 2.X.

**Pull request merged**
