### PR TITLE
[rapids] Update RAPIDS plugin to 22.04 release

### PR DESCRIPTION
**Pull request by nvliyuan**
Signed-off-by: liyuan <yuali@nvidia.com>
update rapids plugin from 22.02 to 22.04, and update xgboost4j jars from 1.4.2-0.2.0 to 1.4.2-0.3.0

### CODE REVIEW

**Comment by viadea** [comment]
@mengdong  @bradmiro  @medb 
The release date for xgboost 1.4.2-0.3.0 is monday(Apr 25) so please wait until it to test/approve.

@nvliyuan

**Comment by viadea** [comment]
@mengdong @bradmiro @medb

The xgboost 1.4.2-0.3.0 is released. 
Please help test and merge.

**Comment by nvliyuan** [comment]
verified
image
image
image

**Comment by viadea** [comment]
Hi Team, 

Currently we are rotating the GPG keys so the gpu driver installation failed.
See below for more details.
https://forums.developer.nvidia.com/t/gpg-error-http-developer-download-nvidia-com-compute-cuda-repos-ubuntu1804-x86-64/212904

So we will try to change the gpu driver script part. @mengdong .
Please stay tuned for this PR.

**Comment by medb** [comment]
@nvliyuan there were couple underlaying failures with Dask init actions that I have fixed today. I have re-triggered presubmit after this but it failed due to GPG key rotation as mentioned above:

```
+ curl -fsSL --retry-connrefused --retry 10 --retry-max-time 30 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-ubuntu1804.pin -o /etc/apt/preferences.d/cuda-repository-pin-600
+ add-apt-repository 'deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64 /'
Hit:1 http://us-central1.gce.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://us-central1.gce.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:3 http://us-central1.gce.archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:4 http://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/ InRelease
Hit:5 https://storage.googleapis.com/goog-dataproc-bigtop-repo-us-central1/1_5_ubu18_20220412_130900-RC01 dataproc InRelease
Hit:6 https://packages.cloud.google.com/apt google-cloud-logging-bionic-all InRelease
Hit:7 https://packages.cloud.google.com/apt google-cloud-monitoring-bionic-all InRelease
Hit:8 https://storage.googleapis.com/dataproc-bigtop-repo/1_5_ubu18_20220412_130900-RC01 dataproc InRelease
Hit:9 https://download.docker.com/linux/ubuntu bionic InRelease
Get:10 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease [1575 B]
Hit:11 https://repo.mysql.com/apt/ubuntu bionic InRelease
Hit:12 https://packages.adoptium.net/artifactory/deb bionic InRelease
Hit:13 http://security.ubuntu.com/ubuntu bionic-security InRelease
Err:10 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
Reading package lists...
W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease' is not signed.
```

**Comment by viadea** [comment]
@medb  I just submitted a new https://github.com/GoogleCloudDataproc/initialization-actions/pull/991  instead. Please close this PR.

**Comment by medb** [comment]
This PR has not changes after https://github.com/GoogleCloudDataproc/initialization-actions/pull/989 was merged.

**Pull request closed without merging**
