### PR TITLE
[gpu] Provide an option to install CUDA 11 to support GCE A2 instances

### PR DESCRIPTION
**Pull request by mengdong**
provide option for cuda 11 to support A2 instances

### CODE REVIEW

**Comment by bradmiro** [comment]
LGTM assuming the tests pass

**Comment by medb** [comment]
Tests are failing on Ubuntu clusters with an error:

```
++ apt-get install -y -q -t bionic-backports --no-install-recommends nvidia-cuda-toolkit nvidia-driver-450 nvidia-kernel-common-450
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package nvidia-driver-450
E: Unable to locate package nvidia-kernel-common-450
``` 

May you fix this issue?

**Comment by mengdong** [comment]
> Tests are failing on Ubuntu clusters with an error:
> 
> ```
> ++ apt-get install -y -q -t bionic-backports --no-install-recommends nvidia-cuda-toolkit nvidia-driver-450 nvidia-kernel-common-450
> Reading package lists...
> Building dependency tree...
> Reading state information...
> E: Unable to locate package nvidia-driver-450
> E: Unable to locate package nvidia-kernel-common-450
> ```
> 
> May you fix this issue?

looks 450 not available for os driver yet, only through nvidia official installation route, I have rollback the os driver to 440

**Pull request merged**
