### PR TITLE
[gpu] Fix bug where attached GPU resources not available after cluster creation

### PR DESCRIPTION
**Pull request by flacode**
Fixes issue [#987](https://github.com/GoogleCloudDataproc/initialization-actions/issues/987)

### CODE REVIEW

**Comment by medb** [comment]
@flacode all tests are passing except a new test on `2.0-rocky` image. May you take a look why it does not work on this new image?

**Comment by flacode** [comment]
@medb, the issue is related to https://github.com/GoogleCloudDataproc/initialization-actions/pull/994/commits

The init script tries to restart the nodemanager service that is not running
```
+ [[ 3.1 != 3.* ]]
+ systemctl status hadoop-yarn-nodemanager
● hadoop-yarn-nodemanager.service - LSB: Hadoop nodemanager
   Loaded: loaded (/etc/rc.d/init.d/hadoop-yarn-nodemanager; generated)
  Drop-In: /etc/systemd/system/hadoop-yarn-nodemanager.service.d
           └─agent-gate.conf, worker-restart.conf
   Active: inactive (dead)
     Docs: man:systemd-sysv-generator(8)
+ [[ Worker == \M\a\s\t\e\r ]]
+ systemctl status hadoop-yarn-nodemanager
● hadoop-yarn-nodemanager.service - LSB: Hadoop nodemanager
   Loaded: loaded (/etc/rc.d/init.d/hadoop-yarn-nodemanager; generated)
  Drop-In: /etc/systemd/system/hadoop-yarn-nodemanager.service.d
           └─agent-gate.conf, worker-restart.conf
   Active: inactive (dead)
     Docs: man:systemd-sysv-generator(8)
```

**Comment by medb** [comment]
@flacode I have backported #994 fix, and it seems that services are restarted as expected:

```
2022-05-06 09:43:14.281 PDT
++ systemctl show hadoop-yarn-resourcemanager.service -p SubState --value

2022-05-06 09:43:14.281 PDT
+ [[ running == \r\u\n\n\i\n\g ]]
2022-05-06 09:43:14.281 PDT
+ systemctl restart hadoop-yarn-resourcemanager.service
2022-05-06 09:43:22.281 PDT
++ systemctl show hadoop-yarn-nodemanager.service -p SubState --value
2022-05-06 09:43:22.281 PDT
+ [[ running == \r\u\n\n\i\n\g ]]
2022-05-06 09:43:22.281 PDT
+ systemctl restart hadoop-yarn-nodemanager.service
```

But new `test_gpu_allocation` test that submits job fails/timeouts on a single-node cluster with `2.0-rocky8` image:
```
22/05/06 16:43:51 WARN org.apache.spark.resource.ResourceProfile: The executor resource config for resource: gpu was specified but no corresponding task resource request was specified.
22/05/06 16:43:52 INFO org.apache.spark.SparkEnv: Registering MapOutputTracker
22/05/06 16:43:52 INFO org.apache.spark.SparkEnv: Registering BlockManagerMaster
22/05/06 16:43:52 INFO org.apache.spark.SparkEnv: Registering BlockManagerMasterHeartbeat
22/05/06 16:43:52 INFO org.apache.spark.SparkEnv: Registering OutputCommitCoordinator
22/05/06 16:43:52 INFO org.sparkproject.jetty.util.log: Logging initialized @4142ms to org.sparkproject.jetty.util.log.Slf4jLog
22/05/06 16:43:52 INFO org.sparkproject.jetty.server.Server: jetty-9.4.40.v20210413; built: 2021-04-13T20:42:42.668Z; git: b881a572662e1943a14ae12e7e1207989f218b74; jvm 1.8.0_322-b06
22/05/06 16:43:52 INFO org.sparkproject.jetty.server.Server: Started @4239ms
22/05/06 16:43:52 INFO org.sparkproject.jetty.server.AbstractConnector: Started ServerConnector@74dbb1ee{HTTP/1.1, (http/1.1)}{0.0.0.0:33803}
22/05/06 16:43:53 INFO org.apache.hadoop.yarn.client.RMProxy: Connecting to ResourceManager at test-gpu-single-2-0-20220506-163039-b9bi-m/10.128.0.33:8032
22/05/06 16:43:53 INFO org.apache.hadoop.yarn.client.AHSProxy: Connecting to Application History server at test-gpu-single-2-0-20220506-163039-b9bi-m/10.128.0.33:10200
22/05/06 16:43:53 INFO org.apache.hadoop.conf.Configuration: found resource resource-types.xml at file:/etc/hadoop/conf.empty/resource-types.xml
22/05/06 16:43:53 INFO org.apache.hadoop.yarn.util.resource.ResourceUtils: Adding resource type - name = yarn.io/gpu, units = , type = COUNTABLE
22/05/06 16:43:54 INFO org.apache.hadoop.yarn.client.api.impl.YarnClientImpl: Submitted application application_1651855397304_0001
22/05/06 16:43:55 INFO org.apache.hadoop.yarn.client.RMProxy: Connecting to ResourceManager at test-gpu-single-2-0-20220506-163039-b9bi-m/10.128.0.33:8030
22/05/06 16:43:58 INFO com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl: Ignoring exception of type GoogleJsonResponseException; verified object already exists with desired state.
22/05/06 16:44:02 WARN org.apache.spark.deploy.yarn.YarnAllocator: Container from a bad node: container_e01_1651855397304_0001_01_000001 on host: test-gpu-single-2-0-20220506-163039-b9bi-m.c.cloud-dataproc-ci.internal. Exit status: -1. Diagnostics: [2022-05-06 16:44:01.368]ResourceHandlerChain.preStart() failed!
[2022-05-06 16:44:01.369]ResourceHandlerChain.preStart() failed!
.
22/05/06 16:44:02 WARN org.apache.spark.scheduler.cluster.YarnSchedulerBackend$YarnSchedulerEndpoint: Requesting driver to remove executor 1 for reason Container from a bad node: container_e01_1651855397304_0001_01_000001 on host: test-gpu-single-2-0-20220506-163039-b9bi-m.c.cloud-dataproc-ci.internal. Exit status: -1. Diagnostics: [2022-05-06 16:44:01.368]ResourceHandlerChain.preStart() failed!
[2022-05-06 16:44:01.369]ResourceHandlerChain.preStart() failed!
.
22/05/06 16:44:05 WARN org.apache.spark.deploy.yarn.YarnAllocator: Container from a bad node: container_e01_1651855397304_0001_01_000002 on host: test-gpu-single-2-0-20220506-163039-b9bi-m.c.cloud-dataproc-ci.internal. Exit status: -1. Diagnostics: [2022-05-06 16:44:04.387]ResourceHandlerChain.preStart() failed!
[2022-05-06 16:44:04.387]ResourceHandlerChain.preStart() failed!
.
22/05/06 16:44:05 WARN org.apache.spark.scheduler.cluster.YarnSchedulerBackend$YarnSchedulerEndpoint: Requesting driver to remove executor 2 for reason Container from a bad node: container_e01_1651855397304_0001_01_000002 on host: test-gpu-single-2-0-20220506-163039-b9bi-m.c.cloud-dataproc-ci.internal. Exit status: -1. Diagnostics: [2022-05-06 16:44:04.387]ResourceHandlerChain.preStart() failed!
[2022-05-06 16:44:04.387]ResourceHandlerChain.preStart() failed!
.
22/05/06 16:44:12 WARN org.apache.spark.deploy.yarn.YarnAllocator: Container from a bad node: container_e01_1651855397304_0001_01_000003 on host: test-gpu-single-2-0-20220506-163039-b9bi-m.c.cloud-dataproc-ci.internal. Exit status: -1. Diagnostics: [2022-05-06 16:44:09.996]ResourceHandlerChain.preStart() failed!
[2022-05-06 16:44:09.996]ResourceHandlerChain.preStart() failed!
.
22/05/06 16:44:12 WARN org.apache.spark.scheduler.cluster.YarnSchedulerBackend$YarnSchedulerEndpoint: Requesting driver to remove executor 3 for reason Container from a bad node: container_e01_1651855397304_0001_01_000003 on host: test-gpu-single-2-0-20220506-163039-b9bi-m.c.cloud-dataproc-ci.internal. Exit status: -1. Diagnostics: [2022-05-06 16:44:09.996]ResourceHandlerChain.preStart() failed!
[2022-05-06 16:44:09.996]ResourceHandlerChain.preStart() failed!
.
22/05/06 16:44:17 WARN org.apache.spark.scheduler.cluster.YarnScheduler: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
22/05/06 16:44:19 WARN org.apache.spark.deploy.yarn.YarnAllocator: Container from a bad node: container_e01_1651855397304_0001_01_000004 on host: test-gpu-single-2-0-20220506-163039-b9bi-m.c.cloud-dataproc-ci.internal. Exit status: -1. Diagnostics: [2022-05-06 16:44:16.209]ResourceHandlerChain.preStart() failed!
[2022-05-06 16:44:16.209]ResourceHandlerChain.preStart() failed!
.
22/05/06 16:44:19 WARN org.apache.spark.scheduler.cluster.YarnSchedulerBackend$YarnSchedulerEndpoint: Requesting driver to remove executor 4 for reason Container from a bad node: container_e01_1651855397304_0001_01_000004 on host: test-gpu-single-2-0-20220506-163039-b9bi-m.c.cloud-dataproc-ci.internal. Exit status: -1. Diagnostics: [2022-05-06 16:44:16.209]ResourceHandlerChain.preStart() failed!
[2022-05-06 16:44:16.209]ResourceHandlerChain.preStart() failed!
```

Maybe we need to configure single-node cluster for this tests a little differently?

**Comment by flacode** [comment]
Looking into the test for rocky8 images.

**Comment by flacode** [comment]
Tests done with single node, image 2.0-rocky8 clusters:

1. Dataproc cluster without init script: job is successful
2. Dataproc cluster with init script and job that does not specify gpu resources: hangs
3. Dataproc cluster with init script and job that specifies gpu resources: hangs

**Comment by medb** [comment]
flacode@ thanks for looking into this - seems like Rocky Linux requires some extra permission configuration for this to work. Because everything else works, I will merge this PR, but feel free to follow up with the fix for Rocky Linux.

**Review by medb — APPROVED** [review]

**Pull request merged**
