### PR TITLE
[gpu-driver]apt-get update fails due to changes in apt repo.

### PR DESCRIPTION
**Pull request by prince-cs**

### CODE REVIEW

**Comment by jayadeep-jayaraman** [comment]
@viadea - pls take a look

**Comment by viadea** [comment]
> @viadea - pls take a look

Actually there is a rick to use `--allow-releaseinfo-change`.
I prefer we fix the root cause instead of using above workaround.
But if GCP team are ok to use this workaround and take the risk for now, i am fine.

**Comment by jayadeep-jayaraman** [comment]
@cjac - can you pls take a look at the previous comment

**Comment by jayadeep-jayaraman** [comment]
We can revert this change now that we have a permanent fix

**Comment by prince-cs** [comment]
Closing this PR as it is no longer required.

**Pull request closed without merging**
