### PR TITLE
[rapids] remove duplicate folder

### PR DESCRIPTION
**Pull request by nvliyuan**
Signed-off-by: liyuan <yuali@nvidia.com>
Since #1028 merged, we should remove sparkRapids folder

### CODE REVIEW

**Comment by viadea** [comment]
@cjac

**Comment by cjac** [comment]
I think we may need to do some tidying up in order to get *all* of the tests to run.  But here's to hoping!

**Comment by cjac** [comment]
jobs are timing out due to io.  I've increased the default pd size and gotten rid of all 'yum update' and 'dnf update' calls.

**Comment by cjac** [comment]
looks like we don't have enough capacity for 1024G disks.  I've reduce the size to 50G again, but changed type from pd-standard to pd-ssd

**Comment by nvliyuan** [comment]
Hi @cjac, not sure why we need these commits just remove a folder, anything I can do?

**Comment by cjac** [comment]
Removing the folder unfortunately triggers a full run of all tests.  These
changes are fixes to the failing actions.  It would probably be better to
fix all of these in their own PRs.

**Comment by nvliyuan** [comment]
> Removing the folder unfortunately triggers a full run of all tests.

Hi @cjac , can we disable this action? Not sure it is reasonable if we want to remove a deprecated folder that will trigger all test.

**Comment by cjac** [comment]
I'm going to prioritize getting all of our tests passing all of the time
instead.  That way, we get both.  And more regular runs of these tests is
critical.  I'm helping to shape Dataproc's direction this coming year, so
we should be able to fit it in if I have my way.

It's been on my mind, as well.

**Comment by cjac** [comment]
@jayadeep-jayaraman - is there any way to temporarily disable the test so we can just remove this excess directory?  I started going down the path of making sure the tests run for all initialization actions, and I didn't get very far.  But we know that deleting the un-used directory, sparkRapids, will not cause any tests to break.  Nothing depends on that directory.  There is just logic to cause commits which create or delete directories to run the entire suite of tests.  Maybe we could change the logic to not trigger any tests on directory removal instead of triggering *all* tests on directory removal.

**Comment by jayadeep-jayaraman** [comment]
I don't think there is anyway today to disable the test. The logic [here](https://github.com/GoogleCloudDataproc/initialization-actions/blob/master/cloudbuild/presubmit.sh#L56-L81) needs to be changed to handle deletions.

**Comment by jayadeep-jayaraman** [comment]
I see that there are lot of changes which are not related to removing the sparkRapids folder. Can you please check the PR once again and remove unwanted changes. Example:- changes to h2o init script, cloud-sql-proxy init script etc.

**Comment by cjac** [comment]
Yes, I'll go through and clean those up tonight.  Thank you for your help with this!

**Comment by cjac** [comment]
sorry, my vacation took priority!

**Comment by cjac** [comment]
This will take a while:

```
2023-02-25T11:01:29.800997373Z All tests will be run: the following BUILD files 'sparkRapids/BUILD' were removed
2023-02-25T11:01:29.801014673Z + echo 'All tests will be run: the following BUILD files '\''sparkRapids/BUILD'\'' were removed'
```

**Comment by cjac** [comment]
well, it hasn't failed yet, which is a good sign.

**Comment by cjac** [comment]
okay, that took too long.  @jayadeep-jayaraman - can you help me to increase the timeout for this deletion?

**Comment by jayadeep-jayaraman** [comment]
Hi @cjac - did you increase the value of timeout in cloudbuild ? If yes can you pls submit that PR so that I can approve that first before testing this ?

**Comment by cjac** [comment]
I did not.  I'll give that a go when I'm at my desk, thanks!

**Comment by nvliyuan** [comment]
Hi @jayadeep-jayaraman , could we remove this folder now?

**Review by jayadeep-jayaraman — APPROVED** [review]

**Pull request merged**
