### PR TITLE
Add Knox init action

### PR DESCRIPTION
**Pull request by yunus**
this pull requests installs and configures apache knox in a dataproc cluster. The goal is to enable BI tools such as Tableau which do not speak dataproc jobs api, in using Hive as a data warehouse.

The features are in readme

The background is in
https://docs.google.com/document/d/1sRVWHepHCAPrKHVfOKt6GZqnbASg1z1L0187IpeCPqo/edit#heading=h.c0uts5ftkk58

### CODE REVIEW

**Comment by yunus** [comment]
@medb I am not able to see what fails. Is it the integration test or do you have any other checks in the pipeline? I don't have access to the [trigger outcome](https://console.cloud.google.com/gcr/builds/90ae86eb-3dfb-42ee-8be5-5d8865f43001?project=786080889824)

**Comment by medb** [comment]
Please, rebase your change on master HEAD, because presubmit identifies changes relative to current master branch HEAD and it includes non-Knox changes because this PR is stale a little

**Comment by medb** [comment]
Knox test failing:
```
Step #2: ======================================================================
Step #2: FAIL: test_knox_localhost_cert [mode=HA, version=1_4, random_prefix=a6r3] (knox.test_knox.KnoxTestCase)
Step #2: ----------------------------------------------------------------------
Step #2: Traceback (most recent call last):
Step #2:   File "/home/ia-tests/.local/lib/python3.5/site-packages/parameterized/parameterized.py", line 518, in standalone_func
Step #2:     return func(*(a + p.args), **p.kwargs)
Step #2:   File "/init-actions/knox/test_knox.py", line 46, in test_knox_localhost_cert
Step #2:     machine_suffix),"localhost")
Step #2:   File "/init-actions/knox/test_knox.py", line 18, in verify_instance
Step #2:     self.__run_test_script(name, cert_type)
Step #2:   File "/init-actions/knox/test_knox.py", line 23, in __run_test_script
Step #2:     name, "bash {} {}".format(self.TEST_SCRIPT_FILE_NAME, cert_type))
Step #2:   File "/init-actions/integration_tests/dataproc_test_case.py", line 177, in assert_instance_command
Step #2:     timeout_in_minutes)
Step #2:   File "/init-actions/integration_tests/dataproc_test_case.py", line 201, in assert_command
Step #2:     cmd, stdout, stderr))
Step #2: AssertionError: 1 != 0 : Failed to execute command:
Step #2: gcloud compute ssh test-knox-ha-1-4-20190811-173929-a75s-m-0 --command="bash verify_knox.sh localhost"
Step #2: STDOUT:
Step #2: 
Step #2: STDERR:
Step #2:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Step #2:                                  Dload  Upload   Total   Spent    Left  Speed
Step #2: 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    18  100    18    0     0   5853      0 --:--:-- --:--:-- --:--:--  6000
Step #2: sudo: /usr/lib/knox/knoxcli.sh: command not found
Step #2:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Step #2:                                  Dload  Upload   Total   Spent    Left  Speed
Step #2: 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0   326    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   326  100   326    0     0    368      0 --:--:-- --:--:-- --:--:--   368
```

**Comment by yunus** [comment]
I fixed the tests. Hope this time works.

**Comment by medb** [comment]
Still failing:
```
Step #2: ======================================================================
Step #2: FAIL: test_knox_localhost_cert [mode=HA, version=1_4, random_prefix=nnki] (knox.test_knox.KnoxTestCase)
Step #2: ----------------------------------------------------------------------
Step #2: Traceback (most recent call last):
Step #2:   File "/home/ia-tests/.local/lib/python3.5/site-packages/parameterized/parameterized.py", line 518, in standalone_func
Step #2:     return func(*(a + p.args), **p.kwargs)
Step #2:   File "/init-actions/knox/test_knox.py", line 46, in test_knox_localhost_cert
Step #2:     machine_suffix),"localhost")
Step #2:   File "/init-actions/knox/test_knox.py", line 18, in verify_instance
Step #2:     self.__run_test_script(name, cert_type)
Step #2:   File "/init-actions/knox/test_knox.py", line 23, in __run_test_script
Step #2:     name, "bash {} {}".format(self.TEST_SCRIPT_FILE_NAME, cert_type))
Step #2:   File "/init-actions/integration_tests/dataproc_test_case.py", line 177, in assert_instance_command
Step #2:     timeout_in_minutes)
Step #2:   File "/init-actions/integration_tests/dataproc_test_case.py", line 201, in assert_command
Step #2:     cmd, stdout, stderr))
Step #2: AssertionError: 1 != 0 : Failed to execute command:
Step #2: gcloud compute ssh test-knox-ha-1-4-20190812-211441-ozsw-m-0 --command="bash verify_knox.sh localhost"
Step #2: STDOUT:
Step #2: Certificate gateway-identity has been successfully exported to: /usr/lib/knox/data/security/keystores/gateway-identity.pem
Step #2: 
Step #2: STDERR:
Step #2:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Step #2:                                  Dload  Upload   Total   Spent    Left  Speed
Step #2: 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    18  100    18    0     0   1366      0 --:--:-- --:--:-- --:--:--  1384
Step #2: + test_type=localhost
Step #2: ++ /usr/share/google/get_metadata_value attributes/dataproc-master
Step #2: + MASTER_NAME=test-knox-ha-1-4-20190812-211441-ozsw-m-0
Step #2: ++ hostname
Step #2: + [[ test-knox-ha-1-4-20190812-211441-ozsw-m-0 == test-knox-ha-1-4-20190812-211441-ozsw-m-0 ]]
Step #2: + sudo -u knox /usr/lib/knox/bin/knoxcli.sh export-cert --type PEM
Step #2: ++ tr -d '[:space:]'
Step #2: ++ hostname -A
Step #2: + sudo sed -i s/localhost/test-knox-ha-1-4-20190812-211441-ozsw-m-0.c.cloud-dataproc-ci.internal/g /etc/knox/conf/topologies/example-hive-pii.xml
Step #2: + sleep 15s
Step #2: + [[ localhost == \l\o\c\a\l\h\o\s\t ]]
Step #2: + curl -i --cacert /usr/lib/knox/data/security/keystores/gateway-identity.pem -u guest:guest-password -X GET 'https://localhost:8443/gateway/example-hive-pii/webhdfs/v1/?op=LISTSTATUS'
Step #2: + grep '200 OK'
Step #2:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Step #2:                                  Dload  Upload   Total   Spent    Left  Speed
Step #2: 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0   326    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   326  100   326    0     0    333      0 --:--:-- --:--:-- --:--:--   333
Step #2: + exit 1
```

**Comment by yunus** [comment]
Sorry for all the issues. It works in my own environment :)
 
The problem happens in between making a change in Knox and till it becomes available for queries. Previously there was only one sleep statement but now I've added a loop to be sure that it passes and some debug output.

While I am on it, I have also added another test for the periodic configuration update.

**Comment by yunus** [comment]
After setting up my own cloud build pipeline and performing automated tests, only once I have seen that knox took more time to update. So I increased the waiting duration. Let's see..

**Comment by yunus** [comment]
Can you share me the fail message? I am not able to see it.

**Comment by yunus** [comment]
Hi, I pushed new updates. Could you please run the tests?

**Comment by yunus** [comment]
@medb I figured out why component gateway fails with this init action. Basically, this init action by default enables SSL and component gateway requires plain HTTP connection. I added an explanation to the README but I have not changed the code. The reason is that I believe the default for Knox connection from any BI tool should be over HTTPS. 

I also have a small patch for the tests which hopefully fix the failing tests.

**Comment by yunus** [comment]
Hi @medb 
Could you please initiate the tests?

**Comment by functicons** [comment]
There seems to be a problem with the CI, see https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/issues/698. @yunus Could you try rebasing your branch to the top of the master?

**Comment by functicons** [comment]
I rebased the PR branch, then test `dataproc-1.5-debian10-tests` failed:

```
+ run_tests
Tests: knox:test_knox knox/services:test_knox/services knox/topologies:test_knox/topologies
+ bazel test --jobs=15 --local_cpu_resources=15 --local_ram_resources=15360 --action_env=INTERNAL_IP_SSH=true --test_output=errors --noshow_progress --noshow_loading_progress --test_arg=--image_version=preview knox:test_knox knox/services:test_knox/services knox/topologies:test_knox/topologies
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
ERROR: Skipping 'knox:test_knox': no such package 'knox': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /init-actions/knox
ERROR: no such package 'knox': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /init-actions/knox
INFO: Elapsed time: 5.506s
INFO: 0 processes.
ERROR: Couldn't start the build. Unable to run tests
++ kubectl get pod presubmit-preview-360ee7e0-a9fd-4452-8b8b-8bbbb4a9682c -o 'go-template={{range .status.containerStatuses}}{{.state.terminated.exitCode}}{{end}}'
+ readonly EXIT_CODE=1
+ EXIT_CODE=1
+ [[ 1 != 0 ]]
+ echo 'Presubmit failed!'
Presubmit failed!
+ exit 1
```

**Comment by cyxxy** [comment]
I needed to fix the test. Will continue the PR in #719

**Pull request closed without merging**
