### PR TITLE
Modify rapids spark to 21.10 from 21.08

### PR DESCRIPTION
**Pull request by viadea**
Modify rapids spark to 21.10 from 21.08

### CODE REVIEW

**Comment by viadea** [comment]
Note: Please do not merge this PR until the xgboost4j jar 1.4.2-0.2.0 are available on maven repo.
I will update this PR once they are available and let you know.thx

**Comment by viadea** [comment]
Hi Team, the xgboost4j jar 1.4.2-0.2.0 are released. So we can move forward with this PR.

@mengdong  @bradmiro FYI.

**Review by bradmiro — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
