### PR TITLE
[dask] merge changes from custom-images

### PR DESCRIPTION
**Pull request by cjac**
including improvements from work with custom-images repo

### CODE REVIEW

**Comment by cjac** [comment]
2.0-ubuntu18 test failed to run this command.  I've added retry logic to the test code.  It feels like an intermittent error, since all other platforms passed this test.

 gcloud compute ssh test-dask-standard-2-0-20241026-192002-cix8-m --zone=us-central1-a --command="/opt/conda/miniconda3/envs/dask/bin/python verify_dask_yarn.py"

**Comment by cjac** [comment]
This time it was only 2.0-ubuntu18 that failed.  It failed in the same way, but when it went to retry, it threw an exception about time not being imported.  So I've imported it now.  Maybe it will work this time?

**Comment by cjac** [comment]
Rocky failed this time, too.  It looks like a race condition related to /var/cache/dnf/metadata_lock.pid ; wait until it is gone before mounting the ram disk.

**Comment by cjac** [comment]
it looks like the yarn tests are passing here, so I should merge the tests into dask-rapids.

**Review by prince-cs — APPROVED** [review]

**Pull request merged**
