### PR TITLE
update rapids version for 24.08 release

### PR DESCRIPTION
**Pull request by nvliyuan**
This pr is to update the spark-rapids script version to 24.08.1

### CODE REVIEW

**Comment by nvliyuan** [comment]
tested

**Comment by nvliyuan** [comment]
Hi @cjac , not sure why the check failed, since the only change is the Rapids version, can we ignore the check and merge the pr?

**Comment by nvliyuan** [comment]
Hi @cjac , could you help share the error log?

**Comment by cjac** [comment]
I'm on vacation right now.  Maybe @prince-cs can help?

**Comment by nvliyuan** [comment]
@prince-cs could you help to merge this pr?  thx

**Comment by prince-cs** [comment]
I have triggered the presubmit tests and will share the error logs if any

**Comment by prince-cs** [comment]
Cluster creation is a success indicating that init action script works. The issue seems to be with the verification script as it is not able to initialize the spark context. Need to look into that. 

Apart from that we can ignore the presubmit failures and merge this PR.

**Comment by prince-cs** [comment]
The test passed in local. Hard to debug on the cloudbuild side.

**Comment by prince-cs** [comment]
2024-09-10 13:49:16.934 IST
Step #2 - "dataproc-2.0-debian10-tests": 2024-09-10T08:19:16.899151444Z java.lang.IllegalArgumentException: This RAPIDS Plugin build does not support Spark build 3.1.3. Supported Spark versions: 3.2.0 {buildver=320}, 3.2.1 {buildver=321}, 3.2.1-cloudera-3.2.7171000 {buildver=321cdh}, 3.2.2 {buildver=322}, 3.2.3 {buildver=323}, 3.2.4 {buildver=324}, 3.3.0 {buildver=330}, 3.3.0-cloudera-3.3.7180 {buildver=330cdh}, 3.3.0-databricks {buildver=330db}, 3.3.1 {buildver=331}, 3.3.2 {buildver=332}, 3.3.2-cloudera-3.3.7190 {buildver=332cdh}, 3.3.2-databricks {buildver=332db}, 3.3.3 {buildver=333}, 3.3.4 {buildver=334}, 3.4.0 {buildver=340}, 3.4.1 {buildver=341}, 3.4.1-databricks {buildver=341db}, 3.4.2 {buildver=342}, 3.4.3 {buildver=343}, 3.5.0 {buildver=350}, 3.5.1 {buildver=351}. Consult the Release documentation at https://nvidia.github.io/spark-rapids/docs/download.html

This is the error which I got from the latest test run

**Comment by sameerz** [comment]
Hi @prince-cs , the RAPIDS spark plugin no longer supports Spark versions less than 3.2.0.  If users want to use Spark 3.1.x, we would point them to an older version of the plugin.  Can we update the tests to Dataproc-2.1 and higher?

**Comment by prince-cs** [comment]
Let me check locally for 2.1+ images and disable for 2.0 and below images

**Comment by prince-cs** [comment]
@nvliyuan I took your changes and then ran the tests for 2.1 and 2.2 images. 

https://github.com/GoogleCloudDataproc/initialization-actions/pull/1232 PR for your reference. I am thinking to get my PR approved and merged and we can close this PR.

**Pull request closed without merging**
