### PR TITLE
update rapids.sh init script for rapids v22.02.0 release

### PR DESCRIPTION
**Pull request by nvliyuan**
Signed-off-by: liyuan <yuali@nvidia.com>
update spark rapids jars to 22.02.0

### CODE REVIEW

**Comment by viadea** [comment]
@bradmiro @mengdong  fyi

**Comment by bradmiro** [comment]
Looks like this was accomplished in https://github.com/GoogleCloudDataproc/initialization-actions/pull/971

**Comment by nvliyuan** [comment]
close this pr since #971 merged

**Pull request closed without merging**
