### PR TITLE
[gpu] Fix YARN configuration

### PR DESCRIPTION
**Pull request by mengdong**
@bradmiro Sorry to bug you, I think your last commit broken spark GPU

### CODE REVIEW

**Comment by bradmiro** [comment]
Nice catch @mengdong , sorry about that and thanks for fixing!

**Comment by mengdong** [comment]
@sameerz @krajendrannv

FYI

**Review by medb — APPROVED** [review]

**Comment by sameerz** [comment]
Thanks for the quick fix!

**Pull request merged**
