### PR TITLE
[rapids] update Spark RAPIDS jars to 21.12

### PR DESCRIPTION
**Pull request by viadea**
update spark rapids jars to 21.12
Signed-off-by: Hao Zhu <hazhu@nvidia.com>

### CODE REVIEW

**Comment by viadea** [comment]
@bradmiro @mengdong

**Comment by sameerz** [comment]
@medb Can you let us know why the presubmit check is failing?  I do not have permissions at https://console.cloud.google.com/navigation-error;errorUrl=%2Fcloud-build%2Fbuilds%2F8245a8a8-72b5-4b23-921c-a0953a42253f%3Fproject%3D786080889824&pli%3D1/permissions?project=786080889824

**Comment by bradmiro** [comment]
> @medb Can you let us know why the presubmit check is failing? I do not have permissions at https://console.cloud.google.com/navigation-error;errorUrl=%2Fcloud-build%2Fbuilds%2F8245a8a8-72b5-4b23-921c-a0953a42253f%3Fproject%3D786080889824&pli%3D1/permissions?project=786080889824

Our presubmits are flaky - rerunning.

**Comment by bradmiro** [comment]
@sameerz @viadea the following failed on a `2.0-debian` cluster

```
+ /opt/conda/miniconda3/envs/mamba/bin/mamba install -y -c rapidsai -c nvidia -c conda-forge -c defaults cudatoolkit=11.0 rapids-blazing=21.12 -p /opt/conda/miniconda3

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.19.1) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['cudatoolkit=11.0', 'rapids-blazing=21.12']


Pinned packages:
  - python 3.8.*
  - python 3.8.*
  - conda 4.9.*
  - r-base 4.0.*
  - r-recommended 4.0.*


Encountered problems while solving:
  - nothing provides requested rapids-blazing 21.12**

nvidia/noarch
nvidia/linux-64
rapidsai/noarch
rapidsai/linux-64
pkgs/r/noarch
pkgs/r/linux-64
pkgs/main/noarch
pkgs/main/linux-64
conda-forge/noarch
conda-forge/linux-64
```

**Comment by sameerz** [comment]
This is failing because rapids-blazing version 21.12 and higher will no longer be published.  @mengdong can you take a look?

**Comment by mengdong** [comment]
Sorry I was OOO, @viadea, could you please change https://github.com/viadea/initialization-actions/blob/update2112/rapids/rapids.sh#L79 to ```
"cudatoolkit=${CUDA_VERSION}" "rapids=${RAPIDS_VERSION}" "dask-sql"

Looks like we also need to update CUDA version to 11.5

which requires change at: https://github.com/viadea/initialization-actions/blob/update2112/rapids/rapids.sh#L18

and add CUDA 11.5 at https://github.com/viadea/initialization-actions/blob/update2112/gpu/install_gpu_driver.sh#L64

If you can add me to your branch, I can help with the change.

**Comment by viadea** [comment]
@mengdong  thanks and done.

@bradmiro try test again?

**Review by medb — APPROVED** [review]

**Pull request merged**
