### PR TITLE
[gpu] Install NVIDIA Container Toolkit

### PR DESCRIPTION
**Pull request by cjac**
[docker] Create a docker-on-yarn configuration script

### CODE REVIEW

**Comment by cjac** [comment]
I know the work on docker_on_yarn.sh will be subsumed on new images by Swati's work.  It might be worthwhile to have it around for use with the current image and prior, though.

**Comment by jayadeep-jayaraman** [comment]
Getting the below error
```
2022-10-26T02:48:31.337545024Z ERROR: no such target '//docker:test_docker': target 'test_docker' not declared in package 'docker' defined by /init-actions/docker/BUILD
```

**Comment by cjac** [comment]
hold off.  I think I need to add some more configs into the script.

**Comment by cjac** [comment]
okay.  I think this should do it.  Do we want to set the default container executor to docker when docker is enabled?  Is `spark.executorEnv.YARN_CONTAINER_RUNTIME_TYPE=docker` too much?

**Comment by cjac** [comment]
I'm seeing the following error when launching a yarn job in a docker container with pyspark:

`22/11/01 16:49:38 ERROR org.apache.spark.SparkContext: Error initializing SparkContext.
org.apache.spark.SparkException: No executor resource configs were not specified for the following task configs: gpu`

I'm going to see if I can narrow down what's causing it and correct it.

**Comment by cjac** [comment]
I have a working version of this attached to issuetracker.google.com/issues/284037562

I need to find how best to refactor this into what's currently in the repo and what would need to go into a new script.

**Comment by cjac** [comment]
This is being implemented with a set of initialization action scripts.

    --initialization-actions ${INIT_ACTIONS_ROOT}/docker_on_yarn.sh,${INIT_ACTIONS_ROOT}/gpu/install_gpu_driver.sh,${INIT_ACTIONS_ROOT}/nvidia_docker.sh \


One script to install docker and ensure that it is properly configured for use with yarn.  This should, in my opinion, be patched into the docker installation scripts in /usr/local/share/google/dataproc/bdutil/components/{post-,}install ; the public issue for this is 289504099[1].

One script to install the gpu driver.  I think the one we patched up in October of last year qualifies.

The third is to install the NVIDIA container toolkit.

You can review these scripts in this attached .tar.gz file.  You'll need to review the code and create env.json from the included example.  Once these scripts all succeed, you will have a cluster against which you can issue these commands:

```
gsutil cp test.py gs://${BUCKET}/
gcloud dataproc jobs submit pyspark \
  --properties="spark:spark.executor.resource.gpu.amount=1" \
  --properties="spark:spark.task.resource.gpu.amount=1" \
  --properties="spark.executorEnv.YARN_CONTAINER_RUNTIME_DOCKER_IMAGE=${YARN_DOCKER_IMAGE}" \
  --cluster=${CLUSTER_NAME} \
  --region ${REGION} gs://${BUCKET}/test.py
```

This will launch the pyspark job in the context of a container using the image specified at `spark.executorEnv.YARN_CONTAINER_RUNTIME_DOCKER_IMAGE`




[1] https://issuetracker.google.com/issues/289504099

**Pull request closed without merging**
