### PR TITLE
[gpu] Fix YARN GPU config fix a2-megagpu-16g

### PR DESCRIPTION
**Pull request by mengdong**
Turns out  `nvidia-smi` for `a2-megapu-16g` is significantly slower, which results in a bad yarn gpu configuration. We have to make a special case for a2-megagpu-16g by manually configure GPU index. 

FYI @sameerz,  @krajendrannv

### CODE REVIEW

**Comment by mengdong** [comment]
> how slow is nvidia-smi? it causes timeout or something? This is only on cluster initialization correct?

nvidia-smi is known to be slow, I think it sequentially pulls information on each GPU. I confirmed that persistenced mode is on, so not sure what else we can do to speed it up.

**Comment by medb** [comment]
Is this still an issue? If so, may you rebase on latest changes in master branch?

**Comment by bradmiro** [comment]
@mengdong is this still relevant?

**Comment by mengdong** [comment]
let me fix the pull request

**Comment by mengdong** [comment]
@bradmiro this PR should be good now, rebased on master

**Comment by mengdong** [comment]
@googlebot I fixed it

**Comment by mengdong** [comment]
@bradmiro would you like to merge this as well?

**Comment by bradmiro** [comment]
Will need to run this again when more resource availability opens up.

**Comment by bradmiro** [comment]
Output for the failed tests: [output.txt](https://github.com/GoogleCloudDataproc/initialization-actions/files/6657669/output.txt)

**Comment by mengdong** [comment]
I will close this pull request given a2-megagpu-16g unlikely used by spark. weirdly I don't see any error from output

**Comment by bradmiro** [comment]
Sounds good, thank you!

**Pull request closed without merging**
