### PR TITLE
Update to RAPIDS Spark 0.5 and 0.19.2

### PR DESCRIPTION
**Pull request by sameerz**
Signed-off-by: Sameer Raheja <sraheja@nvidia.com>

### CODE REVIEW

**Comment by sameerz** [comment]
cc: @mengdong @viadea

**Comment by viadea** [comment]
> cc: @mengdong @viadea

I believe one approval is needed from collaborator @medb .

**Comment by mengdong** [comment]
Adding @bradmiro

**Comment by bradmiro** [comment]
Thanks @mengdong. @sameerz please feel free to cc me going forward for any GPU/RAPIDS changes and I can help ya out.

**Comment by sameerz** [comment]
Hi @bradmiro any feedback on the presubmit-pr failure?

**Comment by bradmiro** [comment]
Looks like we may be having some issues with regional resource availability. I'll keep trying throughout the day.

**Comment by bradmiro** [comment]
Failed for Debain 2.0 test, passted on the rest:
```
Step #9 - "dataproc-2.0-debian10-tests": [2021-05-18 18:09:12.595]Container exited with a non-zero exit code 1. Error file: prelaunch.err.
Step #9 - "dataproc-2.0-debian10-tests": Last 4096 bytes of prelaunch.err :
Step #9 - "dataproc-2.0-debian10-tests": Last 4096 bytes of stderr :
Step #9 - "dataproc-2.0-debian10-tests": eviceManager$.setGpuDeviceAndAcquire(GpuDeviceManager.scala:95)
Step #9 - "dataproc-2.0-debian10-tests": 	at com.nvidia.spark.rapids.GpuDeviceManager$.$anonfun$initializeGpu$1(GpuDeviceManager.scala:122)
Step #9 - "dataproc-2.0-debian10-tests": 	at scala.runtime.java8.JFunction1$mcII$sp.apply(JFunction1$mcII$sp.java:23)
Step #9 - "dataproc-2.0-debian10-tests": 	at scala.Option.map(Option.scala:230)
Step #9 - "dataproc-2.0-debian10-tests": 	at com.nvidia.spark.rapids.GpuDeviceManager$.initializeGpu(GpuDeviceManager.scala:122)
Step #9 - "dataproc-2.0-debian10-tests": 	at com.nvidia.spark.rapids.GpuDeviceManager$.initializeGpuAndMemory(GpuDeviceManager.scala:130)
Step #9 - "dataproc-2.0-debian10-tests": 	at com.nvidia.spark.rapids.RapidsExecutorPlugin.init(Plugin.scala:193)
Step #9 - "dataproc-2.0-debian10-tests": 	at org.apache.spark.internal.plugin.ExecutorPluginContainer.$anonfun$executorPlugins$1(PluginContainer.scala:125)
Step #9 - "dataproc-2.0-debian10-tests": 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
Step #9 - "dataproc-2.0-debian10-tests": 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
Step #9 - "dataproc-2.0-debian10-tests": 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
Step #9 - "dataproc-2.0-debian10-tests": 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
Step #9 - "dataproc-2.0-debian10-tests": 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
Step #9 - "dataproc-2.0-debian10-tests": 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
Step #9 - "dataproc-2.0-debian10-tests": 	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
Step #9 - "dataproc-2.0-debian10-tests": 	at org.apache.spark.internal.plugin.ExecutorPluginContainer.<init>(PluginContainer.scala:113)
Step #9 - "dataproc-2.0-debian10-tests": 	at org.apache.spark.internal.plugin.PluginContainer$.apply(PluginContainer.scala:211)
Step #9 - "dataproc-2.0-debian10-tests": 	at org.apache.spark.internal.plugin.PluginContainer$.apply(PluginContainer.scala:199)
Step #9 - "dataproc-2.0-debian10-tests": 	at org.apache.spark.executor.Executor.$anonfun$plugins$1(Executor.scala:253)
Step #9 - "dataproc-2.0-debian10-tests": 	at org.apache.spark.util.Utils$.withContextClassLoader(Utils.scala:222)
Step #9 - "dataproc-2.0-debian10-tests": 	at org.apache.spark.executor.Executor.<init>(Executor.scala:253)
Step #9 - "dataproc-2.0-debian10-tests": 	at org.apache.spark.executor.CoarseGrainedExecutorBackend$$anonfun$receive$1.applyOrElse(CoarseGrainedExecutorBackend.scala:159)
Step #9 - "dataproc-2.0-debian10-tests": 	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:115)
Step #9 - "dataproc-2.0-debian10-tests": 	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
Step #9 - "dataproc-2.0-debian10-tests": 	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
Step #9 - "dataproc-2.0-debian10-tests": 	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
Step #9 - "dataproc-2.0-debian10-tests": 	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
Step #9 - "dataproc-2.0-debian10-tests": 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
Step #9 - "dataproc-2.0-debian10-tests": 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Step #9 - "dataproc-2.0-debian10-tests": 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Step #9 - "dataproc-2.0-debian10-tests": 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Step #9 - "dataproc-2.0-debian10-tests": 	at java.lang.Thread.run(Thread.java:748)
Step #9 - "dataproc-2.0-debian10-tests": 21/05/18 18:09:11 ERROR org.apache.spark.util.Utils: Uncaught exception in thread shutdown-hook-0
Step #9 - "dataproc-2.0-debian10-tests": java.lang.NullPointerException
Step #9 - "dataproc-2.0-debian10-tests": 	at org.apache.spark.executor.Executor.$anonfun$stop$3(Executor.scala:332)
Step #9 - "dataproc-2.0-debian10-tests": 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
Step #9 - "dataproc-2.0-debian10-tests": 	at org.apache.spark.util.Utils$.withContextClassLoader(Utils.scala:222)
Step #9 - "dataproc-2.0-debian10-tests": 	at org.apache.spark.executor.Executor.stop(Executor.scala:332)
Step #9 - "dataproc-2.0-debian10-tests": 	at org.apache.spark.executor.Executor.$anonfun$new$2(Executor.scala:76)
Step #9 - "dataproc-2.0-debian10-tests": 	at org.apache.spark.util.SparkShutdownHook.run(ShutdownHookManager.scala:214)
Step #9 - "dataproc-2.0-debian10-tests": 	at org.apache.spark.util.SparkShutdownHookManager.$anonfun$runAll$2(ShutdownHookManager.scala:188)
Step #9 - "dataproc-2.0-debian10-tests": 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
Step #9 - "dataproc-2.0-debian10-tests": 	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1996)
Step #9 - "dataproc-2.0-debian10-tests": 	at org.apache.spark.util.SparkShutdownHookManager.$anonfun$runAll$1(ShutdownHookManager.scala:188)
Step #9 - "dataproc-2.0-debian10-tests": 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
Step #9 - "dataproc-2.0-debian10-tests": 	at scala.util.Try$.apply(Try.scala:213)
Step #9 - "dataproc-2.0-debian10-tests": 	at org.apache.spark.util.SparkShutdownHookManager.runAll(ShutdownHookManager.scala:188)
Step #9 - "dataproc-2.0-debian10-tests": 	at org.apache.spark.util.SparkShutdownHookManager$$anon$2.run(ShutdownHookManager.scala:178)
Step #9 - "dataproc-2.0-debian10-tests": 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
Step #9 - "dataproc-2.0-debian10-tests": 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Step #9 - "dataproc-2.0-debian10-tests": 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Step #9 - "dataproc-2.0-debian10-tests": 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Step #9 - "dataproc-2.0-debian10-tests": 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mengdong** [comment]
we need to update the debian driver version here: https://github.com/GoogleCloudDataproc/initialization-actions/blob/master/gpu/install_gpu_driver.sh#L39

@viadea @sameerz what is the driver version you recommend?

Thanks

**Comment by mengdong** [comment]
also please make sure cuda version also compatible:
https://github.com/GoogleCloudDataproc/initialization-actions/blob/master/gpu/install_gpu_driver.sh#L49-L50

**Comment by viadea** [comment]
@mengdong There is no CUDA driver change, the default 11.0 is fine.

@bradmiro Will this test fail even without this PR? say the original 0.4.1 will fail as well?

**Comment by bradmiro** [comment]
@viadea just reverted the Spark version update, let's see

**Comment by viadea** [comment]
@bradmiro  @sameerz 
I tested 2.0-ubuntu18 and it worked fine for me.
And I also tested 2.0-debian10 and I can reproduce the same error.

However as per our doc:https://nvidia.github.io/spark-rapids/docs/download.html 
Rapids accelerator does not support debian, and only support:
`OS: Ubuntu 18.04, Ubuntu 20.04 or CentOS 7, CentOS8`

And also from Debian env, it is using CUDA 11.2 which is not supported by rapids accelerator 0.5.0.
So I think we are fine.

**Comment by bradmiro** [comment]
> @bradmiro @sameerz
> I tested 2.0-ubuntu18 and it worked fine for me.
> And I also tested 2.0-debian10 and I can reproduce the same error.
> 
> However as per our doc:https://nvidia.github.io/spark-rapids/docs/download.html
> Rapids accelerator does not support debian, and only support:
> `OS: Ubuntu 18.04, Ubuntu 20.04 or CentOS 7, CentOS8`
> 
> So I think we are fine.

Sounds good, we can drop Dataproc + Debian support for Spark-RAPIDS.

**Review by bradmiro — APPROVED** [review]

**Comment by bradmiro** [comment]
Thanks!

**Comment by viadea** [comment]
@bradmiro  @mengdong told me that in the past debian env used to work fine.
I will try to test 0.4.1 version debian env firstly and will let you know the results.

**Comment by viadea** [comment]
@bradmiro @mengdong 
I checked with our engineering @jowe on this, and this is due to a bug in the gpu driver installation.
I filed https://github.com/GoogleCloudDataproc/initialization-actions/pull/909 for the fix.
As per my tests, it works fine on debian10 now for rapids accelerator 0.5.0GA

**Pull request merged**
