### PR TITLE
[rapids] Update Spark RAPIDS to 22.06 and XGBoost to DMLC 1.6.1

### PR DESCRIPTION
**Pull request by nvliyuan**
update rapids 2206 release gcp init script and update xgboost version to dmlc 1.6.1

Signed-off-by: liyuan <yuali@nvidia.com>

### CODE REVIEW

**Comment by nvliyuan** [comment]
@medb @viadea Can you please help review? 
Verified.

**Comment by medb** [comment]
> > 
> 
> Hi @nvliyuan , @medb , the DMLC xgboost 1.6.1 does not have pyspark APIs, however your testing script is using pyspark API in below files:
> 
> ```
> test_rapids.py:  XGBOOST_SPARK_TEST_SCRIPT_FILE_NAME = "verify_xgboost_spark.py"
> test_rapids.py:                                self.XGBOOST_SPARK_TEST_SCRIPT_FILE_NAME))
> verify_rapids_dask.py:import xgboost
> verify_rapids_dask.py:    # confirm RAPIDS and xgboost are available
> verify_rapids_dask.py:    dmat = xgboost.DMatrix(df)
> verify_rapids_spark.py:from ml.dmlc.xgboost4j.scala.spark import XGBoostClassificationModel
> verify_xgboost_spark.py:from ml.dmlc.xgboost4j.scala.spark import XGBoostClassificationModel, XGBoostClassifier
> verify_xgboost_spark.py:conf = SparkConf().setAppName("RAPIDS_Accelerator_Spark_XGBoost_test")
> verify_xgboost_spark.py:classifier = XGBoostClassifier(**params).setLabelCol(label).setFeaturesCols(features)
> ```
> 
> Do you want to remove them or change them to scala API?

Is this a long-term strategy/change that DMLC will not support PySpark/Python anymore?

**Comment by nvliyuan** [comment]
> Is this a long-term strategy/change that DMLC will not support PySpark/Python anymore?

It will take some time to support Python, maybe we can disable python testing scripts until DMLC support python api.

**Comment by medb** [comment]
> > Is this a long-term strategy/change that DMLC will not support PySpark/Python anymore?
> 
> It will take some time to support Python, maybe we can disable python testing scripts until DMLC support python api.

In this case, I think that we need to add Scala test (if possible) so we do not lose test coverage and disable Python test until it will be supported again.

**Comment by nvliyuan** [comment]
@medb Do you want to add/disable the tests in a separate pr or just merge this pr?

**Comment by medb** [comment]
Presubmit fails with `2.0-debian10` image, please fix:

```
Traceback (most recent call last):
  File "/tmp/aeff5976d4d04631b6bef6c3dde3acd3/verify_rapids_spark.py", line 3, in <module>
    from ml.dmlc.xgboost4j.scala.spark import XGBoostClassificationModel
ModuleNotFoundError: No module named 'ml'
```

**Comment by nvliyuan** [comment]
> from ml.dmlc.xgboost4j.scala.spark import XGBoostClassificationModel
> ModuleNotFoundError: No module named 'ml'

The reason is DMLC 1.6.1 do not support python api, can you disable python testing scripts?

**Comment by viadea** [comment]
@medb This is the reason why we asked to either:
1. Remove the PySPARK xgboost API test
Or
2. Change it to Scala xgboost  API test.

@nvliyuan  could you put an quick example Scala API test here such as "import xxxx" ?

**Comment by medb** [comment]
In this case, I think that we need to add Scala test as this functionality will not be tested otherwise

**Comment by nvliyuan** [comment]
The scala test code should be like this:
```
import ml.dmlc.xgboost4j.scala.spark.{XGBoostClassifier, XGBoostClassificationModel}
import org.apache.spark.sql.{SparkSession, Row}
import org.apache.spark.ml.evaluation.MulticlassClassificationEvaluator
import org.apache.spark.sql.types.{DoubleType, IntegerType, StructField, StructType}

val label = "1"
val schema = StructType(Array(
    StructField("c0", DoubleType),
    StructField("c1", DoubleType),
    StructField(label, IntegerType)))

val features = schema.filter(_.name != label).map(_.name).toArray

val datas = Seq(Row(1.05, 9.05, 0), 
               Row(2.95, 1.95, 1))
val df = spark.createDataFrame(
      spark.sparkContext.parallelize(datas),schema)

val commParamMap = Map(
  "tree_method" -> "gpu_hist",
  "objective" -> "binary:logistic",
  "num_workers" -> 1,
  "num_round" -> 100)

val xgbClassifier = new XGBoostClassifier(commParamMap)
      .setLabelCol(label)
      .setFeaturesCol(features)

xgbClassifier.fit(df)
```
some spark config:
```
spark.executor.resource.gpu.amount=1
spark.task.resource.gpu.amount=1
spark.dynamicAllocation.enabled=false

```
I verified in notebooks on gcp cluster
image

**Comment by nvliyuan** [comment]
@bradmiro can you please help check why Presubmit fails?

**Comment by bradmiro** [comment]
There appears to be issues with our testing suite - sending back to you @medb

**Comment by medb** [comment]
@nvliyuan please rebase this PR on the upstream `master` branch to fix presubmit issues.

**Comment by nvliyuan** [comment]
@medb done

**Comment by medb** [comment]
Seems like there are issues when installing RAPIDS Python packages for Dask runtime (`--metadata=gpu-driver-provider=NVIDIA,rapids-runtime=DASK,dask-runtime=yarn`):
```
+ mamba install -y --no-channel-priority -c conda-forge -c nvidia -c rapidsai cudatoolkit=11.2 rapids=22.06
conda-forge/linux-64     Using cache
conda-forge/noarch       Using cache

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.15.3) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['cudatoolkit=11.2', 'rapids=22.06']


Pinned packages:
  - python 3.8.*
  - conda 4.9.*
  - python 3.8.*
  - r-base 4.0.*
  - r-recommended 4.0.*


Encountered problems while solving:
  - package arrow-cpp-7.0.0-py38he106920_7_cuda requires libgoogle-cloud >=1.40.2,<1.41.0a0, but none of the providers can be installed

pkgs/main/linux-64        
pkgs/r/noarch             
pkgs/main/noarch          
pkgs/r/linux-64           
rapidsai/noarch           
nvidia/noarch             
nvidia/linux-64           
rapidsai/linux-64
```

**Comment by nvliyuan** [comment]
@medb @bradmiro  just fix the Dask issue, can you please try again?

**Comment by nvliyuan** [comment]
@medb @bradmiro sees the Presubmit still fails, can you please help verify the reason?

**Comment by medb** [comment]
One test is still failing:

```
2022-07-29T19:21:19.021037739Z gcloud compute ssh test-rapids-standard-2-0-20220729-182756-rnaz-m --zone=us-central1-c --command="/opt/conda/default/bin/python verify_rapids_dask.py"
2022-07-29T19:21:19.021061176Z STDOUT:
2022-07-29T19:21:19.021068933Z 
2022-07-29T19:21:19.021076531Z STDERR:
2022-07-29T19:21:19.021083605Z Traceback (most recent call last):
2022-07-29T19:21:19.021090645Z   File "verify_rapids_dask.py", line 1, in <module>
2022-07-29T19:21:19.021097979Z     import cudf
2022-07-29T19:21:19.021105604Z   File "/opt/conda/default/lib/python3.8/site-packages/cudf/__init__.py", line 5, in <module>
2022-07-29T19:21:19.021112824Z     validate_setup()
2022-07-29T19:21:19.021120465Z   File "/opt/conda/default/lib/python3.8/site-packages/cudf/utils/gpu_utils.py", line 20, in validate_setup
2022-07-29T19:21:19.021143127Z     from rmm._cuda.gpu import (
2022-07-29T19:21:19.021151344Z   File "/opt/conda/default/lib/python3.8/site-packages/rmm/__init__.py", line 16, in <module>
2022-07-29T19:21:19.021158660Z     from rmm import mr
2022-07-29T19:21:19.021166300Z   File "/opt/conda/default/lib/python3.8/site-packages/rmm/mr.py", line 14, in <module>
2022-07-29T19:21:19.021173537Z     from rmm._lib.memory_resource import (
2022-07-29T19:21:19.021180668Z   File "/opt/conda/default/lib/python3.8/site-packages/rmm/_lib/__init__.py", line 15, in <module>
2022-07-29T19:21:19.021187971Z     from .device_buffer import DeviceBuffer
2022-07-29T19:21:19.021195113Z   File "device_buffer.pyx", line 1, in init rmm._lib.device_buffer
2022-07-29T19:21:19.021203108Z TypeError: C function cuda.ccudart.cudaStreamSynchronize has wrong signature (expected __pyx_t_4cuda_7ccudart_cudaError_t (__pyx_t_4cuda_7ccudart_cudaStream_t), got cudaError_t (cudaStream_t))
2022-07-29T19:21:19.021224545Z 
2022-07-29T19:21:19.021307348Z 
2022-07-29T19:21:19.021319300Z ----------------------------------------------------------------------
2022-07-29T19:21:19.021327000Z Ran 1 test in 1133.259s
2022-07-29T19:21:19.021375668Z 
2022-07-29T19:21:19.021403111Z FAILED (failures=1)
```

PTAL

**Comment by viadea** [comment]
@medb  this DASK issue should exist before this PR as well since currently we already rollback the DASK RAPIDS version to 22.04.
Can we firstly merge this PR and wait for @mengdong  to fix DASK in the future PR?

**Comment by medb** [comment]
SG, seems like this specific test already broken at HEAD too.

**Review by medb — APPROVED** [review]

**Pull request merged**
