### PR TITLE
Update spark rapids version to 23.12.1 

### PR DESCRIPTION
**Pull request by SurajAralihalli**
This PR

- Updates spark-rapids.sh init script with the latest 23.12.1 (to-date) rapids-4-spark version.

signed-off-by: Suraj Aralihalli [suraj.ara16@gmail.com](mailto:suraj.ara16@gmail.com)

### CODE REVIEW

**Comment by SurajAralihalli** [comment]
@jayadeep-jayaraman Can you review and merge this PR as rapids-4-spark-2.12-23.12.0.jar is publicly available now.

fyi: @viadea @nvliyuan

**Comment by nvliyuan** [comment]
The v2312 jar is already in the [Maven Central](https://repo.maven.apache.org/maven2/com/nvidia/rapids-4-spark_2.12/23.12.0/), LGTM

**Comment by viadea** [comment]
LGTM.

**Comment by nvliyuan** [comment]
Hi @jayadeep-jayaraman could you help check the build error?

**Comment by nvliyuan** [comment]
Hi @jayadeep-jayaraman we found below error info while creating the cluster, is it an issue from dataproc? If so could you help fix it?
```
Err:11 https://repo.mysql.com/apt/ubuntu focal InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B7B3B788A8D3785C
```
```
Get:30 http://security.ubuntu.com/ubuntu focal-security/multiverse Translation-en [5796 B]
Fetched 15.3 MB in 3s (5444 kB/s)
Reading package lists...
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://repo.mysql.com/apt/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B7B3B788A8D3785C
W: Failed to fetch https://repo.mysql.com/apt/ubuntu/dists/focal/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B7B3B788A8D3785C
W: Some index files failed to download. They have been ignored, or old ones used instead.
+ return 0
```

**Comment by cjac** [comment]
There's an argument that can be passed to apt-get update to fix this...

**Comment by cjac** [comment]
https://github.com/GoogleCloudDataproc/initialization-actions/issues/1129

**Comment by cjac** [comment]
But maybe use the -version variant

**Pull request merged**
