### PR TITLE
update rapids.sh to target to v21.12

### PR DESCRIPTION
**Pull request by nvliyuan**
Signed-off-by: liyuan <yuali@nvidia.com>
update rapids.sh to target to rapids plugin v21.12

### CODE REVIEW

**Comment by nvliyuan** [comment]
@viadea @sameerz @mengdong can you please help review?

**Comment by mengdong** [comment]
looks good @bradmiro could you please help?

**Comment by bradmiro** [comment]
@nvliyuan can you please sign the cla and tag me again here after? https://cla.developers.google.com/

**Comment by nvliyuan** [comment]
> @nvliyuan can you please sign the cla and tag me again here after? https://cla.developers.google.com/

already sign the Google Individual CLA with a google account, name:liyuan , Date Signed:Dec 14, 2021 20:53 PST

**Comment by bradmiro** [comment]
> > @nvliyuan can you please sign the cla and tag me again here after? https://cla.developers.google.com/
> 
> already sign the Google Individual CLA with a google account, name:liyuan , Date Signed:Dec 14, 2021 20:53 PST

You will need to sign it with the email associated with this commit, which appears to be your NVIDIA account.

**Comment by ggliyuan** [comment]
> > > @nvliyuan can you please sign the cla and tag me again here after? https://cla.developers.google.com/
> > 
> > 
> > already sign the Google Individual CLA with a google account, name:liyuan , Date Signed:Dec 14, 2021 20:53 PST
> 
> You will need to sign it with the email associated with this commit, which appears to be your NVIDIA account.

I can not open the CLA sign page with my NVIDIA account, I draft another pr #954 with gmail account to do this job.

**Comment by viadea** [comment]
@nvliyuan  i filed https://github.com/GoogleCloudDataproc/initialization-actions/pull/955 for you. 
you can take time to check on CLA.

**Comment by bradmiro** [comment]
Closing as this update is reflected in https://github.com/GoogleCloudDataproc/initialization-actions/pull/955.

**Pull request closed without merging**
