### PR TITLE
[rapids] Update MIG scripts links

### PR DESCRIPTION
**Pull request by nvliyuan**
Signed-off-by: liyuan <yuali@nvidia.com>
update the MIG related scripts links from branch-2206 to branch-2208

### CODE REVIEW

**Comment by viadea** [comment]
@medb  this LGTM.

**Comment by viadea** [comment]
@jayadeep-jayaraman This is a missing PR for 22.08 release. Could you help test and merge it firstly?thx

**Comment by nvliyuan** [comment]
@jayadeep-jayaraman could you share the presubmit failed log?

**Comment by nvliyuan** [comment]
if the error the same as https://github.com/GoogleCloudDataproc/initialization-actions/pull/999#issuecomment-1199959506, maybe we can ignore it.

**Comment by nvliyuan** [comment]
since already merge this change to #1026, we can close this pr

**Pull request closed without merging**
