### PR TITLE
Update spark rapids version to 23.10.0

### PR DESCRIPTION
**Pull request by SurajAralihalli**
This PR 

1. Updates spark-rapids.sh init script with the latest 23.10.0 (to-date) rapids-4-spark version.
2. Fixes issue #1109
3. Installs java ca certificates for deb 10 ahead of driver installation.  

signed-off-by: Suraj Aralihalli [suraj.ara16@gmail.com](mailto:suraj.ara16@gmail.com)

### CODE REVIEW

**Comment by SurajAralihalli** [comment]
@jayadeep-jayaraman The new version of RAPIDS Accelerator is out. Can you review this PR?

FYI @viadea

**Comment by nvliyuan** [comment]
LGTM

**Comment by nvliyuan** [comment]
Hi @jayadeep-jayaraman , could you help confirm why the check failed?

**Review by jayadeep-jayaraman — APPROVED** [review]

**Pull request merged**
