### PR TITLE
Add ldconfig after gpu driver installation completes (new PR)

### PR DESCRIPTION
**Pull request by viadea**
Add ldconfig after gpu driver installation completes

### CODE REVIEW

**Comment by bradmiro** [comment]
@viadea @mengdong is RAPIDS SPARK supported on CentOS? I added the test back in for that, but I may be wrong to have done so. All other tests (including CentOS Dask) passed.

**Comment by viadea** [comment]
> @viadea @mengdong is RAPIDS SPARK supported on CentOS? I added the test back in for that, but I may be wrong to have done so. All other tests (including CentOS Dask) passed.
> 
> If it's not that's fine and I'll remove the test.

yep it is supported on centos 7 and 8.

**Comment by mengdong** [comment]
in the script, we only support centos 8

**Comment by bradmiro** [comment]
@mengdong @viadea apologies for delay, was OOO towards the end of last week.

Here's the error for RAPIDS SPARK on CentOS 8:

```
STDERR:
Job [53c318e247374564ab82cb949b02b847] submitted.
Waiting for job output...
21/06/09 19:06:26 INFO org.spark_project.jetty.util.log: Logging initialized @5169ms
21/06/09 19:06:26 INFO org.spark_project.jetty.server.Server: jetty-9.3.z-SNAPSHOT, build timestamp: unknown, git hash: unknown
21/06/09 19:06:26 INFO org.spark_project.jetty.server.Server: Started @5259ms
21/06/09 19:06:26 INFO org.spark_project.jetty.server.AbstractConnector: Started ServerConnector@6fc77ebe{HTTP/1.1,[http/1.1]}{0.0.0.0:36629}
21/06/09 19:06:27 INFO org.apache.hadoop.yarn.client.RMProxy: Connecting to ResourceManager at test-rapids-single-1-5-20210609-184406-asjy-m/10.128.1.184:8032
21/06/09 19:06:28 INFO org.apache.hadoop.yarn.client.AHSProxy: Connecting to Application History server at test-rapids-single-1-5-20210609-184406-asjy-m/10.128.1.184:10200
21/06/09 19:06:28 INFO org.apache.hadoop.conf.Configuration: found resource resource-types.xml at file:/etc/hadoop/conf.empty/resource-types.xml
21/06/09 19:06:28 INFO org.apache.hadoop.yarn.util.resource.ResourceUtils: Adding resource type - name = yarn.io/gpu, units = , type = COUNTABLE
21/06/09 19:06:28 INFO org.apache.hadoop.yarn.util.resource.ResourceUtils: Adding resource type - name = memory-mb, units = Mi, type = COUNTABLE
21/06/09 19:06:28 INFO org.apache.hadoop.yarn.util.resource.ResourceUtils: Adding resource type - name = vcores, units = , type = COUNTABLE
21/06/09 19:06:31 INFO org.apache.hadoop.yarn.client.api.impl.YarnClientImpl: Submitted application application_1623265557152_0001
21/06/09 19:06:43 ERROR org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend: The YARN application has already ended! It might have been killed or the Application Master may have failed to start. Check the YARN application logs for more details.
21/06/09 19:06:43 ERROR org.apache.spark.SparkContext: Error initializing SparkContext.
org.apache.spark.SparkException: Application application_1623265557152_0001 failed 2 times due to AM Container for appattempt_1623265557152_0001_000002 exited with  exitCode: -1
Failing this attempt.Diagnostics: [2021-06-09 19:06:40.647]ResourceHandlerChain.preStart() failed!
[2021-06-09 19:06:40.647]ResourceHandlerChain.preStart() failed!
For more detailed output, check the application tracking page: http://test-rapids-single-1-5-20210609-184406-asjy-m:8188/applicationhistory/app/application_1623265557152_0001 Then click on links to logs of each attempt.
. Failing the application.
	at org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend.waitForApplication(YarnClientSchedulerBackend.scala:94)
	at org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend.start(YarnClientSchedulerBackend.scala:63)
	at org.apache.spark.scheduler.TaskSchedulerImpl.start(TaskSchedulerImpl.scala:188)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:501)
	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:238)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
21/06/09 19:06:43 INFO org.spark_project.jetty.server.AbstractConnector: Stopped Spark@6fc77ebe{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
21/06/09 19:06:43 WARN org.apache.spark.scheduler.cluster.YarnSchedulerBackend$YarnSchedulerEndpoint: Attempted to request executors before the AM has registered!
21/06/09 19:06:43 WARN org.apache.spark.metrics.MetricsSystem: Stopping a MetricsSystem that is not running
Traceback (most recent call last):
  File "/tmp/53c318e247374564ab82cb949b02b847/verify_rapids_spark.py", line 14, in <module>
    .config(conf=conf) \
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/session.py", line 173, in getOrCreate
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/context.py", line 367, in getOrCreate
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/context.py", line 136, in __init__
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/context.py", line 198, in _do_init
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/context.py", line 306, in _initialize_context
  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1525, in __call__
  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
: org.apache.spark.SparkException: Application application_1623265557152_0001 failed 2 times due to AM Container for appattempt_1623265557152_0001_000002 exited with  exitCode: -1
Failing this attempt.Diagnostics: [2021-06-09 19:06:40.647]ResourceHandlerChain.preStart() failed!
[2021-06-09 19:06:40.647]ResourceHandlerChain.preStart() failed!
For more detailed output, check the application tracking page: http://test-rapids-single-1-5-20210609-184406-asjy-m:8188/applicationhistory/app/application_1623265557152_0001 Then click on links to logs of each attempt.
. Failing the application.
	at org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend.waitForApplication(YarnClientSchedulerBackend.scala:94)
	at org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend.start(YarnClientSchedulerBackend.scala:63)
	at org.apache.spark.scheduler.TaskSchedulerImpl.start(TaskSchedulerImpl.scala:188)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:501)
	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:238)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mengdong** [comment]
looks like this is a GPU installation/configuration script issue for centos, somehow centos couldn't allocate a GPU executor. Irrelevant to this commit. I wonder if we can remove support for  centos on RAPIDS, we can open an issue to investigate this behavior.

**Comment by bradmiro** [comment]
@mengdong that's fine with me, I can remove the RAPIDS Spark test for CentOS. Should I also remove RAPIDS Dask for CentOS even though it passed, in case you feel it may be unreliable?

**Review by bradmiro — APPROVED** [review]

**Comment by bradmiro** [comment]
Thanks!

**Pull request merged**
