### PR TITLE
[gpu] clean up cuda url generation

### PR DESCRIPTION
**Pull request by cjac**
* Create a function is_ubuntu22
* create a variable "shortname" from environment which is listed in [1] 
* merged variables NVIDIA_DEBIAN_REPO_URL, NVIDIA_UBUNTU_REPO_URL into NVIDIA_REPO_URL
* enabled the container toolkit repository for ubuntu as well as debian (it is still only installed on debian 12)

[1] https://developer.download.nvidia.com/compute/machine-learning/repos/

### CODE REVIEW

**Comment by prince-cs** [comment]
The changes work fine for Ubuntu 20.04.

**Review by prince-cs — APPROVED** [review]
LGTM

**Comment by cjac** [comment]
oof.  I forgot that it would run the FULL SUITE if I touched that .py ; I'll revert it for now, but would like to add it as an interstitial.

```
$ git show 8cb3c05ddde17626963ed763c8e6afa31e675272
commit 8cb3c05ddde17626963ed763c8e6afa31e675272
Author: C.J. Collier <cjac@google.com>
Date:   Mon Jul 22 13:53:56 2024 -0700

    improve io performance with pd-balanced

diff --git a/integration_tests/dataproc_test_case.py b/integration_tests/dataproc_test_case.py
index 31c640d..fd0c2c5 100644
--- a/integration_tests/dataproc_test_case.py
+++ b/integration_tests/dataproc_test_case.py
@@ -159,6 +159,9 @@ class DataprocTestCase(parameterized.TestCase):
         args.append("--master-boot-disk-size={}".format(boot_disk_size))
         args.append("--worker-boot-disk-size={}".format(boot_disk_size))
 
+        args.append("--master-boot-disk-type pd-balanced")
+        args.append("--worker-boot-disk-type pd-balanced")
+
         args.append("--format=json")
 
         args.append("--region={}".format(self.REGION))
```

**Comment by cjac** [comment]
I've increased T4 GPUs to 275 to see if that fixes the build failure on 2.0-debian10

**Comment by cjac** [comment]
From the test logs:

```
2024-07-22T21:43:51.919061905Z ERROR: (gcloud.dataproc.clusters.create) INVALID_ARGUMENT: Insufficient 'NVIDIA_T4_GPUS' quota. Requested 3.0, available 0.0. Your resource request exceeds your available quota. See https://cloud.google.com/compute/resource-usage. Use https://cloud.google.com/docs/quotas/view-manage#requesting_higher_quota to request additional quota.
2024-07-22T21:43:51.919069336Z 
2024-07-22T21:43:51.919076391Z 
2024-07-22T21:43:51.919102442Z ----------------------------------------------------------------------
2024-07-22T21:43:51.919112142Z Ran 2 tests in 1415.394s
2024-07-22T21:43:51.919119734Z 
2024-07-22T21:43:51.919127876Z FAILED (failures=1)
2024-07-22T21:43:51.919135966Z ================================================================================
2024-07-22T21:43:52.034644384Z INFO: Found 1 test target...
2024-07-22T21:43:52.127997487Z Target //gpu:test_gpu up-to-date:
2024-07-22T21:43:52.128260095Z   bazel-bin/gpu/test_gpu
2024-07-22T21:43:53.327061241Z INFO: Elapsed time: 2343.920s, Critical Path: 2269.21s
2024-07-22T21:43:53.327189780Z INFO: 21 processes: 38 local.
2024-07-22T21:43:53.408060347Z INFO: Build completed, 1 test FAILED, 21 total actions
2024-07-22T21:43:53.509238567Z //gpu:test_gpu                                                           FAILED in 34 out of 38 in 1433.7s
2024-07-22T21:43:53.509288227Z   Stats over 38 runs: max = 1433.7s, min = 63.2s, avg = 360.4s, dev = 271.2s
```

**Comment by prince-cs** [comment]
> I've increased T4 GPUs quota to 275 to see if that fixes the build failure on 2.0-debian10

Can the quota be bumped to 350?

**Comment by prince-cs** [comment]
The changes looks fine and can be merged. Just concerned about the timeout of 2 hours for the presubmits build. I say, we should make it to 4 hours.

**Comment by cjac** [comment]
Faster is better for me.  Better to resolve the congestion so there is no need for retries.  The actions finish in less than 20m for me, so I expect we can reduce the time to run.

**Comment by cjac** [comment]
> > I've increased T4 GPUs quota to 275 to see if that fixes the build failure on 2.0-debian10
> 
> Can the quota be bumped to 350?

Okay, I've increased to 350

**Comment by cjac** [comment]
Discarding changes to gpu/test_gpu.py as they are being picked up in #1192

**Comment by cjac** [comment]
The error I was receiving was:

```
Caused by: org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.yarn.exceptions.InvalidResourceRequestException): Invalid resource request! Cannot allocate containers as requested resource is greater than maximum allowed allocation. Requested resource type=[yarn.io/gpu], Requested resource=<memory:3072, vCores:1, yarn.io/gpu: 1>, maximum allowed allocation=<memory:6144, vCores:2>, please note that maximum allowed allocation is calculated by scheduler based on maximum resource of registered NodeManagers, which might be less than configured maximum allocation=<memory:6144, vCores:32000, yarn.io/gpu: 9223372036854775807>
```

**Pull request merged**
