### PR TITLE
The install_gpu_driver script should restart services for yarn config…

### PR DESCRIPTION
**Pull request by abellina**
…urations to take effect

The following restart step is needed if the install_gpu_driver.sh script is used in isolation, otherwise Yarn isn't finding the gpu configurations (isolation) that we are setting up here.

@mengdong FYI

Replaces: https://github.com/GoogleCloudDataproc/initialization-actions/pull/975, to see if this re-runs the CLA check since closing and re-opening doesn't look to do that

### CODE REVIEW

**Comment by mengdong** [comment]
@medb @bradmiro could you please help review the pull request? Thanks

**Comment by abellina** [comment]
Hmm, @bradmiro could you comment on why the CI failed?

**Comment by abellina** [comment]
@bradmiro this should be ready for another look

**Review by bradmiro — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
