### PR TITLE
[gpu] Using Debian branches for Ubuntu driver

### PR DESCRIPTION
**Pull request by cjac**
Since the upgrade to kernels which do not allow non-GPL licensing breaks install of ubuntu binary packages, fall back to using nvidia-provided software installers for this platform

### CODE REVIEW

**Comment by cjac** [comment]
manually tested with image version set to
* 2.0-ubuntu18
* 2.1-ubuntu20
* 2.2-ubuntu22
* 2.2-debian12
* 2.1-debian11
* 2.0-debian10

All installations succeeded.

**Comment by prince-cs** [comment]
The presubmits are failing due to quota issues.

**Review by prince-cs — APPROVED** [review]
LGTM

**Comment by cjac** [comment]
test are failing due to lack of T4 GPUs

**Review by kuldeepkk-dev — APPROVED** [review]
LGTM

**Pull request merged**
