### PR TITLE
[kernel] Create scripts to upgrade and revert kernel versions

### PR DESCRIPTION
**Pull request by cjac**
shared/upgrade-kernel.sh: Upgrade kernel to latest version and reboot

shared/revert-kernel.sh: Revert kernel to version capable of building
                       older nvidia drivers and reboot

### CODE REVIEW

**Comment by cjac** [comment]
why is this so flakey?  *sigh*

**Comment by jayadeep-jayaraman** [comment]
Looks like on debian 2.0 cat proc/version command is failing consistently.
```
2022-11-30T02:36:19.172494487Z Traceback (most recent call last):
2022-11-30T02:36:19.172503769Z   File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/kernel/test_kernel.runfiles/io_abseil_py/absl/testing/parameterized.py", line 265, in bound_param_test
2022-11-30T02:36:19.172512010Z     test_method(self, *testcase_params)
2022-11-30T02:36:19.172520179Z   File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/kernel/test_kernel.runfiles/__main__/kernel/test_kernel.py", line 159, in test_downgrade_kernel
2022-11-30T02:36:19.172527696Z     self.verify_kernel("{}-{}".format(self.getClusterName(),
2022-11-30T02:36:19.172535009Z   File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/kernel/test_kernel.runfiles/__main__/kernel/test_kernel.py", line 142, in verify_kernel
2022-11-30T02:36:19.172542438Z     self.assert_instance_command(
2022-11-30T02:36:19.172550329Z   File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/kernel/test_kernel.runfiles/__main__/integration_tests/dataproc_test_case.py", line 270, in assert_instance_command
2022-11-30T02:36:19.172558089Z     ret_code, stdout, stderr = self.assert_command(
2022-11-30T02:36:19.172566534Z   File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/kernel/test_kernel.runfiles/__main__/kernel/test_kernel.py", line 110, in assert_command
2022-11-30T02:36:19.172574244Z     self.assertEqual(
2022-11-30T02:36:19.172582911Z AssertionError: 255 != 0 : Failed to execute command:
2022-11-30T02:36:19.172591273Z gcloud compute ssh test-kernel-standard-2-0-20221130-022923-dmun-m --zone=us-central1-a --command="cat /proc/version"
2022-11-30T02:36:19.172599515Z STDOUT:
2022-11-30T02:36:19.172607290Z 
2022-11-30T02:36:19.172615398Z STDERR:
2022-11-30T02:36:19.172623508Z WARNING: 
```

**Comment by cjac** [comment]
> @cjac - Looks like on debian 2.0 cat proc/version command is failing consistently.
> 
> ```
> 2022-11-30T02:36:19.172494487Z Traceback (most recent call last):
> 2022-11-30T02:36:19.172503769Z   File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/kernel/test_kernel.runfiles/io_abseil_py/absl/testing/parameterized.py", line 265, in bound_param_test
> 2022-11-30T02:36:19.172512010Z     test_method(self, *testcase_params)
> 2022-11-30T02:36:19.172520179Z   File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/kernel/test_kernel.runfiles/__main__/kernel/test_kernel.py", line 159, in test_downgrade_kernel
> 2022-11-30T02:36:19.172527696Z     self.verify_kernel("{}-{}".format(self.getClusterName(),
> 2022-11-30T02:36:19.172535009Z   File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/kernel/test_kernel.runfiles/__main__/kernel/test_kernel.py", line 142, in verify_kernel
> 2022-11-30T02:36:19.172542438Z     self.assert_instance_command(
> 2022-11-30T02:36:19.172550329Z   File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/kernel/test_kernel.runfiles/__main__/integration_tests/dataproc_test_case.py", line 270, in assert_instance_command
> 2022-11-30T02:36:19.172558089Z     ret_code, stdout, stderr = self.assert_command(
> 2022-11-30T02:36:19.172566534Z   File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/kernel/test_kernel.runfiles/__main__/kernel/test_kernel.py", line 110, in assert_command
> 2022-11-30T02:36:19.172574244Z     self.assertEqual(
> 2022-11-30T02:36:19.172582911Z AssertionError: 255 != 0 : Failed to execute command:
> 2022-11-30T02:36:19.172591273Z gcloud compute ssh test-kernel-standard-2-0-20221130-022923-dmun-m --zone=us-central1-a --command="cat /proc/version"
> 2022-11-30T02:36:19.172599515Z STDOUT:
> 2022-11-30T02:36:19.172607290Z 
> 2022-11-30T02:36:19.172615398Z STDERR:
> 2022-11-30T02:36:19.172623508Z WARNING: 
> ```

I talked with Animesh, and he recommended that I add retries.  It has been working for me when running bazel on my workstation.  Let's see if it works on the presubmit script...

**Comment by cjac** [comment]
bazel works fine from my workstation.  :-(

bazel test --jobs=10 --local_test_jobs=10 --flaky_test_attempts=3 --action_env=INTERNAL_IP_SSH=true --test_output=errors --noshow_progress --noshow_loading_progress --test_arg=--image_version=2.0-debian10 kernel:test_kernel

image

**Comment by jayadeep-jayaraman** [comment]
Hi @cjac - is this still an active PR ?

**Comment by cjac** [comment]
No, I think we should turn it down.  This feels like an unsupportable approach.

**Pull request closed without merging**
