### PR TITLE
[gpu] Add support for driver signing

### PR DESCRIPTION
**Pull request by cjac**
* Included new functions used to identify OSs better
* Included support for CUDA 12.4 from NVIDIA on 2.0 and 2.1 images, and CUDA 12.0 from Debian on 2.2 images
* new metadata arguments created to allow users to pass signing materials for dkms and mok keys

### CODE REVIEW

**Comment by prince-cs** [comment]
The quota for GPU drivers still seems to be the issue. Can we request higher quota for GPU drivers?

**Comment by cjac** [comment]
I've also reduced the test's usage of GPUs.  Maybe this will help.

**Comment by cjac** [comment]
I've confirmed that this gpu driver installer works on 2.0.67-debian10

**Comment by cjac** [comment]
And I've confirmed that this gpu driver installer works on 2.1.46-debian11

**Comment by cjac** [comment]
I have confirmed that this gpu driver installer works on 2.0:
```
Thu Jun 20 00:31:07 2024
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.147.05   Driver Version: 525.147.05   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   67C    P0    30W /  70W |      2MiB / 15360MiB |      8%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

```

**Comment by cjac** [comment]
I see that the Debian package managers are more conservative about the modernity of of their Driver and CUDA versions.  I will ask them to include updates in bullseye-backports and bullseye-updates.

**Review by prince-cs — APPROVED** [review]
Is this working with latest production image as well?

**Comment by prince-cs** [comment]
2024-06-26T06:02:58.193347820Z ERROR: (gcloud.dataproc.clusters.create) INVALID_ARGUMENT: Error validating subnetwork 'default' for project 'cloud-dataproc-ci'.

This error only occurs for 2.2 images. So, need to add some network related arguments for 2.2 and also we are disabling the secure boot for 2.1 and 2.2?

**Comment by cjac** [comment]
@jayadeep-jayaraman - this build is failing due to something about the network.  Not related to the code changed here.  Is there any way we can either get the build system fixed or this build force approved?

97cec86a-3ebd-4b5e-8d44-28ec2d33a8ed

**Comment by cjac** [comment]
> Is this working with latest production image as well?

Yes.  I've tested the installers on the latest 2.0, 2.1 and 2.2 images.

I can only get secure boot working with the mok keys on 2.2 images at this time.  I'm seeing strange problems where the certificates included in the DB variables are not being recognized by the kernel on 2.0 and and 2.1 images.  Running with --no-shielded-secure-boot will fix the problem for 2.0 and 2.1.  The argument is not needed with 2.2 custom images built using the new scripts from https://github.com/GoogleCloudDataproc/custom-images/pull/83

**Comment by cjac** [comment]
I think we need to fix the project hosting the build to allow private service connect or whatever was logged as the root cause.  I should have submitted without tests when you approved the changes, Prince.  Can you please re-approve?  I will then push these changes.

**Review by prince-cs — APPROVED** [review]
LGTM

**Review by kuldeepkk-dev — APPROVED** [review]
LGTM. 

Build is failing probably due to different issues, approving based on manual testing done by CJ as per https://github.com/GoogleCloudDataproc/initialization-actions/pull/1190#issuecomment-2192435498

**Comment by cjac** [comment]
Releasing with https://github.com/GoogleCloudDataproc/custom-images/pull/83

**Comment by oniiiiichaaannnnnnn** [comment]
Hi @cjac,

I encountered the following error. 

`yarn.nodemanager.resource-plugins.gpu.allowed-gpu-devices is set to auto, however automatically discovering GPU information failed, please check NodeManager log for more details, as an alternative, admin can specify yarn.nodemanager.resource-plugins.gpu.allowed-gpu-devices manually to enable GPU isolation.`

Do you have any idea about how to fix it?

Thanks

**Comment by cjac** [comment]
Hello @oniiiiichaaannnnnnn ,

Thanks for letting me know!

Can you open a support case and by doing so authorize me to inspect your GCP project?

https://console.cloud.google.com/support

Otherwise, please share with me the command you used to create your cluster so that I can reproduce the issue.

**Pull request merged**
