### PR TITLE
[GPU]Create CentOS gpu installation init action, clean up os driver install to avoid test failure, pin driver to 460.

### PR DESCRIPTION
**Pull request by mengdong**
per https://cloud.google.com/dataproc/docs/concepts/versioning/dataproc-versions#centos_images, dataproc 2.0 support centos images, this pull request add gpu libraries installation for centos8 which dataproc 2.0 supports.

BTW, the installation is so slow, I have to use `--initialization-action-timeout=60m`

@bradmiro @sameerz @viadea please review. Thanks

### CODE REVIEW

**Comment by viadea** [comment]
@mengdong I did a quick test and it works fine for me.

**Comment by sameerz** [comment]
@bradmiro can you share the build failure?

**Comment by bradmiro** [comment]
@sameerz sorry, there still seems to be issues with resource allocation. I'll have to see if there's a sensible workaround next week.

**Comment by bradmiro** [comment]
We have a helpful build failure! See below, failure is from Debian 1.3, but **did** pass on CentOS :) 

```
+ eval 'apt-get install -y --allow-unauthenticated libnccl2=2.8.4-1+cuda11.0 libnccl-dev=2.8.4-1+cuda11.0'
++ apt-get install -y --allow-unauthenticated libnccl2=2.8.4-1+cuda11.0 libnccl-dev=2.8.4-1+cuda11.0
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '2.8.4-1+cuda11.0' for 'libnccl2' was not found
E: Version '2.8.4-1+cuda11.0' for 'libnccl-dev' was not found
+ sleep 5
+ (( i++ ))
+ (( i < 10 ))
+ eval 'apt-get install -y --allow-unauthenticated libnccl2=2.8.4-1+cuda11.0 libnccl-dev=2.8.4-1+cuda11.0'
++ apt-get install -y --allow-unauthenticated libnccl2=2.8.4-1+cuda11.0 libnccl-dev=2.8.4-1+cuda11.0
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '2.8.4-1+cuda11.0' for 'libnccl2' was not found
E: Version '2.8.4-1+cuda11.0' for 'libnccl-dev' was not found
+ sleep 5
+ (( i++ ))
+ (( i < 10 ))
+ eval 'apt-get install -y --allow-unauthenticated libnccl2=2.8.4-1+cuda11.0 libnccl-dev=2.8.4-1+cuda11.0'
++ apt-get install -y --allow-unauthenticated libnccl2=2.8.4-1+cuda11.0 libnccl-dev=2.8.4-1+cuda11.0
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '2.8.4-1+cuda11.0' for 'libnccl2' was not found
E: Version '2.8.4-1+cuda11.0' for 'libnccl-dev' was not found
+ sleep 5
+ (( i++ ))
+ (( i < 10 ))
+ eval 'apt-get install -y --allow-unauthenticated libnccl2=2.8.4-1+cuda11.0 libnccl-dev=2.8.4-1+cuda11.0'
++ apt-get install -y --allow-unauthenticated libnccl2=2.8.4-1+cuda11.0 libnccl-dev=2.8.4-1+cuda11.0
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '2.8.4-1+cuda11.0' for 'libnccl2' was not found
E: Version '2.8.4-1+cuda11.0' for 'libnccl-dev' was not found
+ sleep 5
+ (( i++ ))
+ (( i < 10 ))
+ eval 'apt-get install -y --allow-unauthenticated libnccl2=2.8.4-1+cuda11.0 libnccl-dev=2.8.4-1+cuda11.0'
++ apt-get install -y --allow-unauthenticated libnccl2=2.8.4-1+cuda11.0 libnccl-dev=2.8.4-1+cuda11.0
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '2.8.4-1+cuda11.0' for 'libnccl2' was not found
E: Version '2.8.4-1+cuda11.0' for 'libnccl-dev' was not found
+ sleep 5
+ (( i++ ))
+ (( i < 10 ))
+ return 1
```

**Comment by mengdong** [comment]
Hello. @bradmiro does NCCL install on debian ever work? I found out this change works for debian 2.0. Maybe debian 1.3 doesn't work with the newer nccl? 

I needed to upgrade nccl to 2.8.4 because that is the oldest available version for centOS. 

Maybe we can set an older nccl version for 1.x dataproc images?

Please let me know your thought on this.

**Comment by bradmiro** [comment]
These tests have passed before, maybe we can set 2.7.8 for older images? Or maybe 1.3 / 1.4? Centos is supported as of 1.5.

**Comment by mengdong** [comment]
Do you know what is the meta label that distinguish dataproc 2.0 from 1.x images? We can just add a if else on the default nccl version.

**Comment by bradmiro** [comment]
`$DATAPROC_VERSION` exists in the environment and points to the `major.minor` version.  [Here's](https://github.com/GoogleCloudDataproc/initialization-actions/blob/4eaccbc1418c8d351ffe13f7e809b81712f2780e/mlvm/mlvm.sh#L66) an example of how we use this in a different init action.

**Comment by mengdong** [comment]
@bradmiro could you please give the test another try? Thanks

**Comment by mengdong** [comment]
@bradmiro per our email I have added an additional change to pin driver version to 460 to fix issues on ubuntu and possible future error.

**Comment by bradmiro** [comment]
Failed on debian 1.5 -
```
Installing collected packages: six, protobuf, googleapis-common-protos, pyparsing, packaging, pyasn1, pyasn1-modules, cachetools, rsa, google-auth, grpcio, google-api-core, proto-plus, mypy-extensions, typing-inspect, pyyaml, libcst, google-cloud-monitoring
  Found existing installation: six 1.12.0
    Uninstalling six-1.12.0:
      Successfully uninstalled six-1.12.0
Successfully installed cachetools-4.2.2 google-api-core-1.28.0 google-auth-1.30.1 google-cloud-monitoring-2.0.0 googleapis-common-protos-1.53.0 grpcio-1.38.0 libcst-0.3.19 mypy-extensions-0.4.3 packaging-20.9 proto-plus-1.18.1 protobuf-3.17.1 pyasn1-0.4.8 pyasn1-modules-0.2.8 pyparsing-2.4.7 pyyaml-5.4.1 rsa-4.7.2 six-1.16.0 typing-inspect-0.6.0
+ cat
+ systemctl daemon-reload
+ systemctl --no-reload --now enable gpu-utilization-agent.service
Created symlink /etc/systemd/system/multi-user.target.wants/gpu-utilization-agent.service → /lib/systemd/system/gpu-utilization-agent.service.
+ echo 'GPU metrics agent successfully deployed.'
GPU metrics agent successfully deployed.
+ configure_gpu_exclusive_mode
+ local spark_version
++ spark-submit --version
++ head -n1
++ sed -n 's/.*version[[:blank:]]\+\([0-9]\+\.[0-9]\).*/\1/p'
+ spark_version=2.4
+ [[ 2.4 != 3.* ]]
+ nvidia-smi -c EXCLUSIVE_PROCESS
Failed to initialize NVML: Driver/library version mismatch
```

**Comment by mengdong** [comment]
I had reverted the driver version for debian. Please let me know if this time it works.

**Comment by bradmiro** [comment]
Failed again with the same error.

**Comment by mengdong** [comment]
@bradmiro  But it is working for me in my local test, for both 460.73.01 and 460.56, are you sure it is debian 1.5? Thanks

**Comment by bradmiro** [comment]
Yes, will try again.

**Comment by bradmiro** [comment]
@mengdong same error in Dataproc 1.5-Debian

**Comment by mengdong** [comment]
Could you share the test parameter?

**Comment by bradmiro** [comment]
All Dataproc 1.5-Debian tests failed.

All Dataproc 1.X passed except 1.5-Debian. 2.0 tests did not run yet since the 1.5 test failed.

**Comment by mengdong** [comment]
Is 1.5.37-debian10 the version you used in the test or the next one?

**Comment by bradmiro** [comment]
The tests always run on the latest patch versions, so 1.5.37 should be correct.

**Comment by mengdong** [comment]
@bradmiro thanks to @viadea we figured out that it is OS driver install that caused your test failure, I propose we delete OS driver install to avoid future problems.

Could you please run the test again. Thanks!

**Comment by bradmiro** [comment]
@mengdong @viadea Good catch, I can confirm from the test logs that this only failed for the OS-installed tests. I am fine with removing it. Let's do so in this PR and then we will rebase https://github.com/GoogleCloudDataproc/initialization-actions/pull/909. 

Also, what is the use case that has a long installation time? Is it just the CentOS install?

**Comment by mengdong** [comment]
yes, just for centos

**Comment by mengdong** [comment]
@bradmiro could you try to run the test again? I think all test should pass now.

**Comment by bradmiro** [comment]
@mengdong gotcha, I missed your earlier commit, my bad.

Can you please remove the OS-based test cases as well?

**Comment by mengdong** [comment]
@bradmiro Thanks for the reminder, yeah, I removed the OS test cases now.

**Review by bradmiro — APPROVED** [review]

**Comment by bradmiro** [comment]
Thanks!

**Pull request merged**
