### PR TITLE
[livy] #871 | Python3 support

### LINKED ISSUE #871: Livy with Python 3.X
By default Livy uses Python 2.7. Due to deprecation of that branch only Python3 should be used for DataProc 1.4+

Solution:

Minoconda:
```
export PYSPARK_PYTHON=/opt/conda/miniconda3/bin/python3
export PYSPARK_DRIVER_PYTHON=/opt/conda/miniconda3/bin/python3
```

Anaconda:
```
export PYSPARK_PYTHON=/opt/conda/anaconda/bin/python3
export PYSPARK_DRIVER_PYTHON=/opt/conda/anaconda/bin/python3
```

Paths from: https://cloud.google.com/dataproc/docs/tutorials/python-configuration#image_version_14

### PR DESCRIPTION
**Pull request by wsmolak**
fixes #871

### CODE REVIEW

**Comment by medb** [comment]
Thank you for contribution!

**Review by medb — APPROVED** [review]

**Comment by wsmolak** [comment]
> Thank you for contribution!

Thanks for quick merge :)

**Comment by medb** [comment]
We have weekly releases, so it should be out by end of the next week.

**Pull request merged**
