### PR TITLE
[rapids] Update Spark RAPIDS to 22.10

### PR DESCRIPTION
**Pull request by nvliyuan**
update spark-rapids dataproc init script for v2210 release and merge changes from #1016 and #1017 

Signed-off-by: liyuan <yuali@nvidia.com>

### CODE REVIEW

**Comment by nvliyuan** [comment]
@medb @viadea @pulkit-jain-G  Can you please help review?
Verified.

**Comment by viadea** [comment]
LGTM

**Comment by nvliyuan** [comment]
@pulkit-jain-G could you help share the presubmit error?

**Comment by jayadeep-jayaraman** [comment]
The tests are failing because of 

```
Most of the disks failed. 1/1 local-dirs usable space is below configured utilization percentage/no more usable space [ /hadoop/yarn/nm-local-dir : used space above threshold of 90.0% ] ; 1/1 log-dirs usable space is below configured utilization percentage/no more usable space [ /var/log/hadoop-yarn/userlogs : used space above threshold of 90.0% 
```

Can you please increase the disk size when creating the cluster. 

Also, there is a total timeout of 1 hour 30 minutes mentioned in `cloudbuild.yaml` and because of the above errors the tests are running for 90 minutes and then we are seeing the below error in the test logs

```
TIMEOUT
ERROR: context deadline exceeded
```

**Comment by nvliyuan** [comment]
@jayadeep-jayaraman updated, could you help build again?

**Comment by pulkit-jain-G** [comment]
@nvliyuan build failed with following error - 

2022-10-31T04:35:00.768812447Z ================================================================================
2022-10-31T04:35:00.768817467Z ==================== Test output for //rapids:test_rapids (shard 5 of 6):
2022-10-31T04:35:00.768822547Z Running tests under Python 3.8.10: /usr/bin/python3
2022-10-31T04:35:00.768827627Z [ RUN      ] RapidsTestCase.test_rapids_spark('SINGLE', ['m'], 'type=nvidia-tesla-p100')
2022-10-31T04:35:00.768833297Z [  FAILED  ] RapidsTestCase.test_rapids_spark('SINGLE', ['m'], 'type=nvidia-tesla-p100')
2022-10-31T04:35:00.768838867Z ======================================================================
2022-10-31T04:35:00.768843797Z FAIL: test_rapids_spark('SINGLE', ['m'], 'type=nvidia-tesla-p100') (__main__.RapidsTestCase)
2022-10-31T04:35:00.768875567Z test_rapids_spark('SINGLE', ['m'], 'type=nvidia-tesla-p100') (__main__.RapidsTestCase)
2022-10-31T04:35:00.768882137Z test_rapids_spark('SINGLE', ['m'], 'type=nvidia-tesla-p100')
2022-10-31T04:35:00.768887847Z ----------------------------------------------------------------------
2022-10-31T04:35:00.768892667Z Traceback (most recent call last):
2022-10-31T04:35:00.768897837Z   File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/rapids/test_rapids.runfiles/io_abseil_py/absl/testing/parameterized.py", line 265, in bound_param_test
2022-10-31T04:35:00.768902617Z     test_method(self, *testcase_params)
2022-10-31T04:35:00.768907647Z   File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/rapids/test_rapids.runfiles/__main__/rapids/test_rapids.py", line 96, in test_rapids_spark
2022-10-31T04:35:00.768912587Z     self.createCluster(
2022-10-31T04:35:00.768924347Z   File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/rapids/test_rapids.runfiles/__main__/integration_tests/dataproc_test_case.py", line 170, in createCluster
2022-10-31T04:35:00.768929547Z     _, stdout, _ = self.assert_command(
2022-10-31T04:35:00.768956947Z   File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/rapids/test_rapids.runfiles/__main__/integration_tests/dataproc_test_case.py", line 322, in assert_command
2022-10-31T04:35:00.768963537Z     self.assertEqual(
2022-10-31T04:35:00.768968257Z AssertionError: 1 != 0 : Failed to execute command:
2022-10-31T04:35:00.768977517Z gcloud dataproc clusters create test-rapids-single-1-5-20221031-043101-hzu6 --single-node --image-version=1.5-debian10 --optional-components=ANACONDA --initialization-actions='gs://dataproc-init-actions-test-cloud-dataproc-ci/20221031-043055-nd0n/gpu/install_gpu_driver.sh,gs://dataproc-init-actions-test-cloud-dataproc-ci/20221031-043055-nd0n/rapids/rapids.sh' --initialization-action-timeout=30m --metadata=gpu-driver-provider=NVIDIA,rapids-runtime=SPARK,cuda-version=10.1 --master-accelerator=type=nvidia-tesla-p100 --worker-accelerator=type=nvidia-tesla-p100 --master-machine-type=n1-standard-4 --worker-machine-type=n1-standard-4 --master-boot-disk-size=200GB --worker-boot-disk-size=200GB --format=json --region=us-central1 --max-age=2h
2022-10-31T04:35:00.768982307Z STDOUT:
2022-10-31T04:35:00.768986547Z 
2022-10-31T04:35:00.768991247Z STDERR:
2022-10-31T04:35:00.768995817Z Waiting on operation [projects/cloud-dataproc-ci/regions/us-central1/operations/b2a0d450-92a1-3e34-a054-74c811ecea3e].
2022-10-31T04:35:00.769000627Z Waiting for cluster creation operation...
2022-10-31T04:35:00.769005187Z WARNING: For PD-Standard without local SSDs, we strongly recommend provisioning 1TB or larger to ensure consistently high I/O performance. See https://cloud.google.com/compute/docs/disks/performance for information on disk I/O performance.
2022-10-31T04:35:00.769010347Z ..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................done.
2022-10-31T04:35:00.769015377Z ERROR: (gcloud.dataproc.clusters.create) Operation [projects/cloud-dataproc-ci/regions/us-central1/operations/b2a0d450-92a1-3e34-a054-74c811ecea3e] failed: Initialization action failed. Failed action 'gs://dataproc-init-actions-test-cloud-dataproc-ci/20221031-043055-nd0n/gpu/install_gpu_driver.sh', see output in: gs://dataproc-108de5de-43c2-4a4b-979a-adebc15a58a8-us-central1/google-cloud-dataproc-metainfo/596e0e9d-fa71-4bec-bf4b-1b17734ecfa0/test-rapids-single-1-5-20221031-043101-hzu6-m/dataproc-initialization-script-0_output.
2022-10-31T04:35:00.769019807Z 
2022-10-31T04:35:00.769044647Z 
2022-10-31T04:35:00.769056747Z ----------------------------------------------------------------------
2022-10-31T04:35:00.769061497Z Ran 1 test in 252.606s
2022-10-31T04:35:00.769066177Z 
2022-10-31T04:35:00.769071237Z FAILED (failures=1)
2022-10-31T04:35:00.769076077Z ================================================================================

**Comment by nvliyuan** [comment]
@pulkit-jain-G  skip image 1.5, could you help build again?

**Comment by nvliyuan** [comment]
@pulkit-jain-G seems the job timeout again, could you share the log?

**Comment by nvliyuan** [comment]
@pulkit-jain-G seems the job failed before timeout, could you share the log?

**Comment by pulkit-jain-G** [comment]
@nvliyuan 

2022-11-01T11:05:00.311692603Z ================================================================================
2022-11-01T11:05:00.311699920Z ==================== Test output for //rapids:test_rapids (shard 3 of 6):
2022-11-01T11:05:00.311706971Z Running tests under Python 3.8.10: /usr/bin/python3
2022-11-01T11:05:00.311714075Z [ RUN      ] RapidsTestCase.test_rapids_dask('STANDARD', ['m', 'w-0'], 'type=nvidia-tesla-p100', 'yarn')
2022-11-01T11:05:00.311725358Z [  FAILED  ] RapidsTestCase.test_rapids_dask('STANDARD', ['m', 'w-0'], 'type=nvidia-tesla-p100', 'yarn')
2022-11-01T11:05:00.315790019Z ======================================================================
2022-11-01T11:05:00.315879081Z FAIL: test_rapids_dask('STANDARD', ['m', 'w-0'], 'type=nvidia-tesla-p100', 'yarn') (__main__.RapidsTestCase)
2022-11-01T11:05:00.315890453Z test_rapids_dask('STANDARD', ['m', 'w-0'], 'type=nvidia-tesla-p100', 'yarn') (__main__.RapidsTestCase)
2022-11-01T11:05:00.315898499Z test_rapids_dask('STANDARD', ['m', 'w-0'], 'type=nvidia-tesla-p100', 'yarn')
2022-11-01T11:05:00.315923727Z ----------------------------------------------------------------------
2022-11-01T11:05:00.315931971Z Traceback (most recent call last):
2022-11-01T11:05:00.315941845Z   File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/rapids/test_rapids.runfiles/io_abseil_py/absl/testing/parameterized.py", line 265, in bound_param_test
2022-11-01T11:05:00.315949296Z     test_method(self, *testcase_params)
2022-11-01T11:05:00.315959382Z   File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/rapids/test_rapids.runfiles/__main__/rapids/test_rapids.py", line 81, in test_rapids_dask
2022-11-01T11:05:00.315967857Z     self.verify_dask_instance("{}-{}".format(self.getClusterName(),
2022-11-01T11:05:00.315975302Z   File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/rapids/test_rapids.runfiles/__main__/rapids/test_rapids.py", line 34, in verify_dask_instance
2022-11-01T11:05:00.315982898Z     self.assert_instance_command(name, verify_cmd)
2022-11-01T11:05:00.315991347Z   File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/rapids/test_rapids.runfiles/__main__/integration_tests/dataproc_test_case.py", line 270, in assert_instance_command
2022-11-01T11:05:00.315998564Z     ret_code, stdout, stderr = self.assert_command(
2022-11-01T11:05:00.316005816Z   File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/rapids/test_rapids.runfiles/__main__/integration_tests/dataproc_test_case.py", line 322, in assert_command
2022-11-01T11:05:00.316013336Z     self.assertEqual(
2022-11-01T11:05:00.316023398Z AssertionError: 1 != 0 : Failed to execute command:
2022-11-01T11:05:00.316033537Z gcloud compute ssh test-rapids-standard-2-0-20221101-103844-p2ev-m --zone=us-central1-c --command="/opt/conda/default/bin/python verify_rapids_dask.py"
2022-11-01T11:05:00.316041392Z STDOUT:
2022-11-01T11:05:00.316048250Z 
2022-11-01T11:05:00.316055729Z STDERR:
2022-11-01T11:05:00.316064315Z /opt/conda/default/lib/python3.8/site-packages/scipy/__init__.py:138: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.4)
2022-11-01T11:05:00.316071815Z   warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion} is required for this version of "
2022-11-01T11:05:00.316079244Z Traceback (most recent call last):
2022-11-01T11:05:00.316088431Z   File "verify_rapids_dask.py", line 1, in <module>
2022-11-01T11:05:00.316096365Z     import cudf
2022-11-01T11:05:00.316104338Z   File "/opt/conda/default/lib/python3.8/site-packages/cudf/__init__.py", line 5, in <module>
2022-11-01T11:05:00.316111749Z     validate_setup()
2022-11-01T11:05:00.316119051Z   File "/opt/conda/default/lib/python3.8/site-packages/cudf/utils/gpu_utils.py", line 20, in validate_setup
2022-11-01T11:05:00.316125807Z     from rmm._cuda.gpu import (
2022-11-01T11:05:00.316132820Z   File "/opt/conda/default/lib/python3.8/site-packages/rmm/__init__.py", line 16, in <module>
2022-11-01T11:05:00.316139076Z     from rmm import mr
2022-11-01T11:05:00.316148848Z   File "/opt/conda/default/lib/python3.8/site-packages/rmm/mr.py", line 14, in <module>
2022-11-01T11:05:00.316156881Z     from rmm._lib.memory_resource import (
2022-11-01T11:05:00.316164111Z   File "/opt/conda/default/lib/python3.8/site-packages/rmm/_lib/__init__.py", line 15, in <module>
2022-11-01T11:05:00.316171080Z     from .device_buffer import DeviceBuffer
2022-11-01T11:05:00.316185726Z   File "device_buffer.pyx", line 1, in init rmm._lib.device_buffer
2022-11-01T11:05:00.316193552Z TypeError: C function cuda.ccudart.cudaStreamSynchronize has wrong signature (expected __pyx_t_4cuda_7ccudart_cudaError_t (__pyx_t_4cuda_7ccudart_cudaStream_t), got cudaError_t (cudaStream_t))
2022-11-01T11:05:00.316200435Z 
2022-11-01T11:05:00.316207050Z 
2022-11-01T11:05:00.316216713Z ----------------------------------------------------------------------
2022-11-01T11:05:00.316224702Z Ran 1 test in 1587.313s
2022-11-01T11:05:00.316231380Z 
2022-11-01T11:05:00.316238323Z FAILED (failures=1)
2022-11-01T11:05:00.316245325Z ================================================================================

**Comment by nvliyuan** [comment]
@pulkit-jain-G it is the same issue as [this](https://github.com/GoogleCloudDataproc/initialization-actions/pull/999#issuecomment-1199959506), I just disable `test_rapids_dask`, could you help build again?

**Comment by pulkit-jain-G** [comment]
@nvliyuan Build again failed. try to rerun and will post logs if failed again

**Comment by nvliyuan** [comment]
I test in local and found that there is a bug in test_rapis.py test_non_default_cuda_versions because we do not have gpu in master node so do not need to verify nvidia-smi in master node;just updated, could you help build again

**Comment by pulkit-jain-G** [comment]
@nvliyuan Build succeeded.

**Comment by nvliyuan** [comment]
@viadea @mengdong could you help review again?

**Comment by viadea** [comment]
LGTM

**Comment by nvliyuan** [comment]
@pulkit-jain-G could you help merge this pr? thanks

**Review by pulkit-jain-G — APPROVED** [review]
LGTM

**Pull request merged**
