### PR TITLE
Update TonY, TF and PyTorch

### LINKED ISSUE #616: Upgrade Dataproc initialization to latest TF version and TonY version
Upgrade to TF 1.15
Upgrade to latest Tony Client

### PR DESCRIPTION
**Pull request by bradmiro**
tony: 0.3.23 -> 0.3.24
tensorflow: 1.13.2 -> 1.15.0
torch (pytorch): 0.4.1.post2 -> 1.4.0
torchvision: 0.2.1 -> 0.5.0

Fixes #616

### CODE REVIEW

**Comment by medb** [comment]
Tests fails with:
```
++ /usr/share/google/get_metadata_value attributes/torch_version
++ echo 1.4.0
+ torch_version=1.4.0
+ local torchvision_version
++ /usr/share/google/get_metadata_value attributes/torchvision_version
++ echo 0.5.0
+ torchvision_version=0.5.0
+ cd /opt/tony/TonY-samples/deps
+ virtualenv -p python3 tf
/usr/bin/python3: can't find '__main__' module in '/usr/local/lib/python2.7/dist-packages/virtualenv-16.7.9-py2.7.egg/virtualenv.py'
Running virtualenv with interpreter /usr/bin/python3
```

**Comment by bradmiro** [comment]
Haven't forgotten about this, I ran into an issue where the PyTorch test was hanging and still need to figure out what's going on.

**Comment by bradmiro** [comment]
Closing this, I am working on a fresh PR.

**Pull request closed without merging**
