### PR TITLE
[rapids] Add XGBoost GPU test for Spark 3.0

### PR DESCRIPTION
**Pull request by mengdong**

### CODE REVIEW

**Comment by medb** [comment]
Test failing, you need to add `verify_xgboost_spark.py` to `BUILD` file: https://github.com/GoogleCloudDataproc/initialization-actions/blob/65740c7ae527357a978a814f770116827918435e/rapids/BUILD#L25

**Comment by mengdong** [comment]
Thanks, I've made the change.

**Comment by medb** [comment]
Tests are failing on 1.5 images:

```
==================== Test output for //rapids:test_rapids (shard 2 of 2):
Running tests under Python 3.5.2: /usr/bin/python3
[ RUN      ] RapidsTestCase.test_rapids_spark('STANDARD', ['w-0'], 'type=nvidia-tesla-p100')
[  FAILED  ] RapidsTestCase.test_rapids_spark('STANDARD', ['w-0'], 'type=nvidia-tesla-p100')
======================================================================
FAIL: test_rapids_spark('STANDARD', ['w-0'], 'type=nvidia-tesla-p100') (__main__.RapidsTestCase)
test_rapids_spark('STANDARD', ['w-0'], 'type=nvidia-tesla-p100') (__main__.RapidsTestCase)
test_rapids_spark('STANDARD', ['w-0'], 'type=nvidia-tesla-p100')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/rapids/test_rapids.runfiles/io_abseil_py/absl/testing/parameterized.py", line 265, in bound_param_test
    test_method(self, *testcase_params)
  File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/rapids/test_rapids.runfiles/__main__/rapids/test_rapids.py", line 93, in test_rapids_spark
    self.verify_spark_job()
  File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/rapids/test_rapids.runfiles/__main__/rapids/test_rapids.py", line 47, in verify_spark_job
    self.XGBOOST_SPARK_TEST_SCRIPT_FILE_NAME))
  File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/rapids/test_rapids.runfiles/__main__/integration_tests/dataproc_test_case.py", line 269, in assert_dataproc_job
    job_params), timeout_in_minutes)
  File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/rapids/test_rapids.runfiles/__main__/integration_tests/dataproc_test_case.py", line 293, in assert_command
    cmd, stdout, stderr))
AssertionError: 1 != 0 : Failed to execute command:
gcloud dataproc jobs submit pyspark --cluster=test-rapids-standard-1-5-20201006-055505-8dlk --region=us-central1 gs://dataproc-init-actions-test-cloud-dataproc-ci/20201006-055502-y6e8/rapids/verify_xgboost_spark.py
STDOUT:

STDERR:
Job [192dfa0621174038b32ec3016746d6bc] submitted.
Waiting for job output...
20/10/06 06:06:13 INFO org.spark_project.jetty.util.log: Logging initialized @4753ms
20/10/06 06:06:13 INFO org.spark_project.jetty.server.Server: jetty-9.3.z-SNAPSHOT, build timestamp: unknown, git hash: unknown
20/10/06 06:06:13 INFO org.spark_project.jetty.server.Server: Started @4871ms
20/10/06 06:06:13 INFO org.spark_project.jetty.server.AbstractConnector: Started ServerConnector@4d073bc2{HTTP/1.1,[http/1.1]}{0.0.0.0:43667}
20/10/06 06:06:14 INFO org.apache.hadoop.yarn.client.RMProxy: Connecting to ResourceManager at test-rapids-standard-1-5-20201006-055505-8dlk-m/10.128.0.77:8032
20/10/06 06:06:15 INFO org.apache.hadoop.yarn.client.AHSProxy: Connecting to Application History server at test-rapids-standard-1-5-20201006-055505-8dlk-m/10.128.0.77:10200
20/10/06 06:06:15 INFO org.apache.hadoop.conf.Configuration: resource-types.xml not found
20/10/06 06:06:15 INFO org.apache.hadoop.yarn.util.resource.ResourceUtils: Unable to find 'resource-types.xml'.
20/10/06 06:06:15 INFO org.apache.hadoop.yarn.util.resource.ResourceUtils: Adding resource type - name = yarn.io/gpu, units = , type = COUNTABLE
20/10/06 06:06:15 INFO org.apache.hadoop.yarn.util.resource.ResourceUtils: Adding resource type - name = memory-mb, units = Mi, type = COUNTABLE
20/10/06 06:06:15 INFO org.apache.hadoop.yarn.util.resource.ResourceUtils: Adding resource type - name = vcores, units = , type = COUNTABLE
20/10/06 06:06:17 INFO org.apache.hadoop.yarn.client.api.impl.YarnClientImpl: Submitted application application_1601964062543_0002
Traceback (most recent call last):
  File "/tmp/192dfa0621174038b32ec3016746d6bc/verify_xgboost_spark.py", line 42, in <module>
    classifier = XGBoostClassifier(**params).setLabelCol(label).setFeaturesCols(features)
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/__init__.py", line 110, in wrapper
  File "/usr/lib/spark/jars/xgboost4j-spark_2.x-1.0.0-Beta5.jar/sparkxgb/xgboost.py", line 85, in __init__
  File "/usr/lib/spark/jars/xgboost4j-spark_2.x-1.0.0-Beta5.jar/sparkxgb/common.py", line 69, in __init__
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/ml/wrapper.py", line 67, in _new_java_obj
  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1525, in __call__
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling None.ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.
: java.lang.NoClassDefFoundError: scala/Product$class
	at ml.dmlc.xgboost4j.scala.spark.TrackerConf.<init>(XGBoost.scala:55)
	at ml.dmlc.xgboost4j.scala.spark.TrackerConf$.apply(XGBoost.scala:58)
	at ml.dmlc.xgboost4j.scala.spark.params.GeneralParams$class.$init$(GeneralParams.scala:187)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.<init>(XGBoostClassifier.scala:52)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.<init>(XGBoostClassifier.scala:57)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:238)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: scala.Product$class
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 16 more

20/10/06 06:06:31 INFO org.spark_project.jetty.server.AbstractConnector: Stopped Spark@4d073bc2{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
ERROR: (gcloud.dataproc.jobs.submit.pyspark) Job [192dfa0621174038b32ec3016746d6bc] failed with error:
Google Cloud Dataproc Agent reports job failure. If logs are available, they can be found at:
```

Seems like we should not run XGBoost GPU test on 1.5 images?

**Comment by mengdong** [comment]
You are right, thought I made that change last time but the change wasn't there...  both sparkSQL and XGBoost test run in 2.x dataproc images

**Review by medb — APPROVED** [review]

**Pull request merged**
