### PR TITLE
[rapids] Update XGBoost to 1.6.0

### PR DESCRIPTION
**Pull request by ggliyuan**
update spark rapids init script to v22.04.0
Signed-off-by: liyuan [yuali@nvidia.com](mailto:yuali@nvidia.com)

### CODE REVIEW

**Comment by nvliyuan** [comment]
verified it works
image
image

**Comment by nvliyuan** [comment]
@bradmiro @mengdong @viadea 
This pr is ready to review, but I can not mark a draft pr as ready because I don't have write access. Can someone help?
image

**Comment by viadea** [comment]
this pr looks good to me. @bradmiro @mengdong .

**Comment by medb** [comment]
One of the tests failed on 2.0 Debian image:

```
==================== Test output for //rapids:test_rapids (shard 6 of 6):
Running tests under Python 3.8.10: /usr/bin/python3
[ RUN      ] RapidsTestCase.test_rapids_spark('STANDARD', ['w-0'], 'type=nvidia-tesla-p100')
[  FAILED  ] RapidsTestCase.test_rapids_spark('STANDARD', ['w-0'], 'type=nvidia-tesla-p100')
======================================================================
FAIL: test_rapids_spark('STANDARD', ['w-0'], 'type=nvidia-tesla-p100') (__main__.RapidsTestCase)
test_rapids_spark('STANDARD', ['w-0'], 'type=nvidia-tesla-p100') (__main__.RapidsTestCase)
test_rapids_spark('STANDARD', ['w-0'], 'type=nvidia-tesla-p100')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/rapids/test_rapids.runfiles/io_abseil_py/absl/testing/parameterized.py", line 265, in bound_param_test
    test_method(self, *testcase_params)
  File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/rapids/test_rapids.runfiles/__main__/rapids/test_rapids.py", line 113, in test_rapids_spark
    self.verify_spark_job()
  File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/rapids/test_rapids.runfiles/__main__/rapids/test_rapids.py", line 45, in verify_spark_job
    self.assert_dataproc_job(
  File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/rapids/test_rapids.runfiles/__main__/integration_tests/dataproc_test_case.py", line 281, in assert_dataproc_job
    ret_code, stdout, stderr = self.assert_command(
  File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/rapids/test_rapids.runfiles/__main__/integration_tests/dataproc_test_case.py", line 305, in assert_command
    self.assertEqual(
AssertionError: 1 != 0 : Failed to execute command:
gcloud dataproc jobs submit pyspark --cluster=test-rapids-standard-2-0-20220422-175534-ojcu --region=us-central1 gs://dataproc-init-actions-test-cloud-dataproc-ci/20220422-175518-3ni7/rapids/verify_rapids_spark.py
STDOUT:

STDERR:
Job [5884a2f815d0463d9bc5788dcc27581d] submitted.
Waiting for job output...
Traceback (most recent call last):
  File "/tmp/5884a2f815d0463d9bc5788dcc27581d/verify_rapids_spark.py", line 3, in <module>
    from ml.dmlc.xgboost4j.scala.spark import XGBoostClassificationModel
ModuleNotFoundError: No module named 'ml'
ERROR: (gcloud.dataproc.jobs.submit.pyspark) Job [5884a2f815d0463d9bc5788dcc27581d] failed with error:
Job failed with message [ModuleNotFoundError: No module named 'ml']. Additional details can be found at:
https://console.cloud.google.com/dataproc/jobs/5884a2f815d0463d9bc5788dcc27581d?project=cloud-dataproc-ci&region=us-central1
gcloud dataproc jobs wait '5884a2f815d0463d9bc5788dcc27581d' --region 'us-central1' --project 'cloud-dataproc-ci'
https://console.cloud.google.com/storage/browser/dataproc-108de5de-43c2-4a4b-979a-adebc15a58a8-us-central1/google-cloud-dataproc-metainfo/000e098a-e924-473b-8583-1973650d0f2b/jobs/5884a2f815d0463d9bc5788dcc27581d/
gs://dataproc-108de5de-43c2-4a4b-979a-adebc15a58a8-us-central1/google-cloud-dataproc-metainfo/000e098a-e924-473b-8583-1973650d0f2b/jobs/5884a2f815d0463d9bc5788dcc27581d/driveroutput
```

@ggliyuan may you fix it?

**Comment by viadea** [comment]
@medb in this PR, we replaced our old xgboost 1.4.2-0.2.0 jars with the latest one from dmlc 1.6.0 jars.
In this 1.6.0 jar, we do not have pyspark API yet. That is why your test failed.

I just checked your ./rapids/verify_rapids_spark.py and it only has one line by loading the python lib,but it does not actually doing anything about it.
```
from ml.dmlc.xgboost4j.scala.spark import XGBoostClassificationModel
```

Can you remove this line from your test script ./rapids/verify_rapids_spark.py?

**Comment by medb** [comment]
@ggliyuan Do we still need this PR?

**Comment by nvliyuan** [comment]
> @ggliyuan Do we still need this PR?

no, can you please help close?

**Pull request closed without merging**
