### PR TITLE
[dask][rapids] Updating dask-yarn, rapids for dask-yarn GPU support

### PR DESCRIPTION
**Pull request by bradmiro**
Bumping dask-yarn from 0.8 to 0.9 to accommodate GPU config. 

Update RAPIDS to include dask-yarn gpu config.

FYI @quasiben, @mengdong, @sameerz

### CODE REVIEW

**Comment by quasiben** [comment]
Thanks for updating @bradmiro

**Comment by mengdong** [comment]
Hi @bradmiro , could you please let us know if this change passed the test. Thanks!

**Comment by bradmiro** [comment]
Having some issues getting this to work, following up with @quasiben over email before fixing upstream.

**Comment by bradmiro** [comment]
@quasiben @mengdong tests passed, LMK if you have any feedback

**Review by ranu010101 — APPROVED** [review]

**Pull request merged**
