### PR TITLE
Change rapids spark version to 21.06.0

### PR DESCRIPTION
**Pull request by viadea**
Change rapids spark version to 21.06.0

### CODE REVIEW

**Comment by viadea** [comment]
@mengdong  @sameerz

**Comment by mengdong** [comment]
@bradmiro  could you merge this? Thanks

**Comment by bradmiro** [comment]
Errors are resource-related, I will comment on this thread if any action is needed from the NVIDIA team.

**Review by bradmiro — APPROVED** [review]

**Comment by bradmiro** [comment]
Thanks!

**Pull request merged**
