### PR TITLE
[gpu] Account for rocky9 kernel-devel-$(uname -r) moving to vault

### PR DESCRIPTION
**Pull request by cjac**
modified:   gpu/install_gpu_driver.sh

* inlining conditional blocks to reduce lines while maintaining readability
* cache results from some frequently-used programs
* decrease verbosity of apt-get with additional -q
* wrap nvidia-smi in a function which manages cache some
* add a work-around for kernel-devel-$(uname -r) missing from rocky9 repo
* use time to determine how long the long tasks take

modified:   gpu/test_gpu.py

* removed code skipping rocky tests

### CODE REVIEW

**Review by prince-cs — APPROVED** [review]

**Comment by cjac** [comment]
https://github.com/GoogleCloudDataproc/initialization-actions/pull/1207#issuecomment-2267084553
> /gcbrun

This test passed.
BGiLKotSkedyuBN

**Pull request merged**
