### PR TITLE
[spark-rapids] Updating spark-rapids version to 24.08.1 and enabling the tests to run only for 2.1 and 2.2 images

### PR DESCRIPTION
**Pull request by prince-cs**

### CODE REVIEW

**Comment by nvliyuan** [comment]
LGTM

**Review by kuldeepkk-dev — COMMENTED** [review]
"Not supported in pre 2.0 images" - Can we modify this wordings since we don't support 2.0 either? 

Something like "Not supported in 2.0 and earlier images"?

**Review by kuldeepkk-dev — APPROVED** [review]

**Pull request merged**
