### PR TITLE
Adding test which deploys cluster with nvidia drivers and cuda instal…

### PR DESCRIPTION
**Pull request by prince-cs**
Adding test which deploys cluster with nvidia drivers and cuda installed and monitoring enabled. Also runs the spark job to ensure gpu utilisation and working of monitoring.

### CODE REVIEW

**Review by bcheena — APPROVED** [review]

**Comment by jayadeep-jayaraman** [comment]
did we check why the tests are failing ?

**Review by jayadeep-jayaraman — APPROVED** [review]

**Comment by bcheena** [comment]
Here are the errors:
```
Step #9 - "dataproc-2.1-rocky8-tests": 2023-11-29T10:37:31.451377546Z ERROR: (gcloud.dataproc.clusters.create) Operation [projects/cloud-dataproc-ci/regions/us-central1/operations/21834ad6-b472-359a-9ab5-5fc8264422ea] failed: Multiple Errors:
Step #9 - "dataproc-2.1-rocky8-tests": 2023-11-29T10:37:31.451385583Z  - Initialization action failed. Failed action 'gs://dataproc-init-actions-test-cloud-dataproc-ci/20231129-101722-1u09/gpu/install_gpu_driver.sh', see output in: gs://dataproc-108de5de-43c2-4a4b-979a-adebc15a58a8-us-central1/google-cloud-dataproc-metainfo/9a39f76b-bbe2-48e9-93b4-b4d6644db338/test-gpu-standard-2-1-20231129-101811-5vpk-m/dataproc-initialization-script-0_output
Step #9 - "dataproc-2.1-rocky8-tests": 2023-11-29T10:37:31.451400530Z  - Initialization action failed. Failed action 'gs://dataproc-init-actions-test-cloud-dataproc-ci/20231129-101722-1u09/gpu/install_gpu_driver.sh', see output in: gs://dataproc-108de5de-43c2-4a4b-979a-adebc15a58a8-us-central1/google-cloud-dataproc-metainfo/9a39f76b-bbe2-48e9-93b4-b4d6644db338/test-gpu-standard-2-1-20231129-101811-5vpk-w-0/dataproc-initialization-script-0_output
Step #9 - "dataproc-2.1-rocky8-tests": 2023-11-29T10:37:31.451407505Z  - Initialization action failed. Failed action 'gs://dataproc-init-actions-test-cloud-dataproc-ci/20231129-101722-1u09/gpu/install_gpu_driver.sh', see output in: gs://dataproc-108de5de-43c2-4a4b-979a-adebc15a58a8-us-central1/google-cloud-dataproc-metainfo/9a39f76b-bbe2-48e9-93b4-b4d6644db338/test-gpu-standard-2-1-20231129-101811-5vpk-w-1/dataproc-initialization-script-0_output.
Step #9 - "dataproc-2.1-rocky8-tests": 2023-11-29T10:37:31.451414186Z 
Step #9 - "dataproc-2.1-rocky8-tests": 2023-11-29T10:37:31.451420558Z 
Step #9 - "dataproc-2.1-rocky8-tests": 2023-11-29T10:37:31.451427560Z ----------------------------------------------------------------------
Step #9 - "dataproc-2.1-rocky8-tests": 2023-11-29T10:37:31.451434478Z Ran 1 test in 523.900s
Step #9 - "dataproc-2.1-rocky8-tests": 2023-11-29T10:37:31.451440754Z 
Step #9 - "dataproc-2.1-rocky8-tests": 2023-11-29T10:37:31.451447801Z FAILED (failures=1)
```
And the output of init script:
```
++ dnf -y -q update
Error: 
 Problem: The operation would result in removing the following protected packages: systemd
```

**Comment by prince-cs** [comment]
For this error, the issue seems to be with the rocky OS. We need to create a separate ticket for this and resolve it accordingly.

**Pull request merged**
