### PR TITLE
Update to work with dask-rapids 22.10

### PR DESCRIPTION
**Pull request by cjac**
Fix for issue #1039

### CODE REVIEW

**Comment by cjac** [comment]
@nvliyuan -
@viadea  -
Can you please let me know what you think of these changes once you're back from the holiday break.
I wish you the best in the new year!

**Comment by nvliyuan** [comment]
LGTM, thanks

**Review by kuldeepkk-dev — APPROVED** [review]
Fix for https://github.com/GoogleCloudDataproc/initialization-actions/issues/1039 with dask-rapids 22.10

**Pull request merged**
