### PR TITLE
[knox]: correct bucket name in README and install rsync to fix Debian 10-based images installation

### PR DESCRIPTION
**Pull request by yunus**
I fixed the bucket address in the README.

Rsync is missing in Dataproc 1.5 image. I have added that to the list of software to download for compatibility.

### CODE REVIEW

**Comment by medb** [comment]
Debian 10 failing with `curl: (60) SSL certificate problem: EE certificate key too weak` error:

```
==================== Test output for //knox:test_knox (shard 2 of 6):
Running tests under Python 3.5.2: /usr/bin/python3
[ RUN      ] KnoxTestCase.test_knox_hostname_cert('HA', ['m-1', 'm-0'])
[  FAILED  ] KnoxTestCase.test_knox_hostname_cert('HA', ['m-1', 'm-0'])
======================================================================
FAIL: test_knox_hostname_cert('HA', ['m-1', 'm-0']) (__main__.KnoxTestCase)
test_knox_hostname_cert('HA', ['m-1', 'm-0']) (__main__.KnoxTestCase)
test_knox_hostname_cert('HA', ['m-1', 'm-0'])
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/knox/test_knox.runfiles/io_abseil_py/absl/testing/parameterized.py", line 265, in bound_param_test
    test_method(self, *testcase_params)
  File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/knox/test_knox.runfiles/__main__/knox/test_knox.py", line 73, in test_knox_hostname_cert
    "hostname")
  File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/knox/test_knox.runfiles/__main__/knox/test_knox.py", line 20, in verify_instance
    self._run_test_script(name, cert_type)
  File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/knox/test_knox.runfiles/__main__/knox/test_knox.py", line 26, in _run_test_script
    name, "bash {} {}".format(self.TEST_SCRIPT_FILE_NAME, cert_type))
  File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/knox/test_knox.runfiles/__main__/integration_tests/dataproc_test_case.py", line 240, in assert_instance_command
    timeout_in_minutes)
  File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/knox/test_knox.runfiles/__main__/integration_tests/dataproc_test_case.py", line 293, in assert_command
    cmd, stdout, stderr))
AssertionError: 1 != 0 : Failed to execute command:
gcloud compute ssh test-knox-ha-1-3-20200718-192639-kff7-m-0 --command="bash verify_knox.sh hostname"
STDOUT:
Certificate gateway-identity has been successfully exported to: /usr/lib/knox/data/security/keystores/gateway-identity.pem

STDERR:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

+ readonly test_type=hostname
+ test_type=hostname
++ /usr/share/google/get_metadata_value attributes/knox-gw-config
+ readonly KNOX_GW_CONFIG_GCS=gs://dataproc-init-actions-test-cloud-dataproc-ci/20200718-192632-lp0o/knox
+ KNOX_GW_CONFIG_GCS=gs://dataproc-init-actions-test-cloud-dataproc-ci/20200718-192632-lp0o/knox
++ /usr/share/google/get_metadata_value attributes/dataproc-master
+ readonly MASTER_NAME=test-knox-ha-1-3-20200718-192639-kff7-m-0
+ MASTER_NAME=test-knox-ha-1-3-20200718-192639-kff7-m-0
++ hostname
+ [[ test-knox-ha-1-3-20200718-192639-kff7-m-0 == test-knox-ha-1-3-20200718-192639-kff7-m-0 ]]
+ test_installation example-hive-pii
+ topology=example-hive-pii
+ sudo -u knox /usr/lib/knox/bin/knoxcli.sh export-cert --type PEM
++ hostname -A
++ tr -d '[:space:]'
+ sudo sed -i s/localhost/test-knox-ha-1-3-20200718-192639-kff7-m-0.c.cloud-dataproc-ci.internal/g /etc/knox/conf/topologies/example-hive-pii.xml
+ [[ hostname == \l\o\c\a\l\h\o\s\t ]]
+ [[ hostname == \h\o\s\t\n\a\m\e ]]
++ hostname -A
++ tr -d '[:space:]'
+ host_address=test-knox-ha-1-3-20200718-192639-kff7-m-0.c.cloud-dataproc-ci.internal
+ for _ in {1..10}
+ sleep 15s
+ curl -i --cacert /usr/lib/knox/data/security/keystores/gateway-identity.pem -u guest:guest-password -X GET 'https://test-knox-ha-1-3-20200718-192639-kff7-m-0.c.cloud-dataproc-ci.internal:8443/gateway/example-hive-pii/webhdfs/v1/?op=LISTSTATUS'
+ grep '200 OK'
+ tee test_output
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

curl: (60) SSL certificate problem: EE certificate key too weak
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
+ cat test_output
+ for _ in {1..10}
+ sleep 15s
+ curl -i --cacert /usr/lib/knox/data/security/keystores/gateway-identity.pem -u guest:guest-password -X GET 'https://test-knox-ha-1-3-20200718-192639-kff7-m-0.c.cloud-dataproc-ci.internal:8443/gateway/example-hive-pii/webhdfs/v1/?op=LISTSTATUS'
+ grep '200 OK'
+ tee test_output
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

curl: (60) SSL certificate problem: EE certificate key too weak
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
+ cat test_output
+ for _ in {1..10}
+ sleep 15s
+ curl -i --cacert /usr/lib/knox/data/security/keystores/gateway-identity.pem -u guest:guest-password -X GET 'https://test-knox-ha-1-3-20200718-192639-kff7-m-0.c.cloud-dataproc-ci.internal:8443/gateway/example-hive-pii/webhdfs/v1/?op=LISTSTATUS'
+ grep '200 OK'
+ tee test_output
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

curl: (60) SSL certificate problem: EE certificate key too weak
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
+ cat test_output
+ for _ in {1..10}
+ sleep 15s
+ curl -i --cacert /usr/lib/knox/data/security/keystores/gateway-identity.pem -u guest:guest-password -X GET 'https://test-knox-ha-1-3-20200718-192639-kff7-m-0.c.cloud-dataproc-ci.internal:8443/gateway/example-hive-pii/webhdfs/v1/?op=LISTSTATUS'
+ grep '200 OK'
+ tee test_output
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

curl: (60) SSL certificate problem: EE certificate key too weak
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
+ cat test_output
+ for _ in {1..10}
+ sleep 15s
+ curl -i --cacert /usr/lib/knox/data/security/keystores/gateway-identity.pem -u guest:guest-password -X GET 'https://test-knox-ha-1-3-20200718-192639-kff7-m-0.c.cloud-dataproc-ci.internal:8443/gateway/example-hive-pii/webhdfs/v1/?op=LISTSTATUS'
+ grep '200 OK'
+ tee test_output
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

curl: (60) SSL certificate problem: EE certificate key too weak
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
+ cat test_output
+ for _ in {1..10}
+ sleep 15s
+ curl -i --cacert /usr/lib/knox/data/security/keystores/gateway-identity.pem -u guest:guest-password -X GET 'https://test-knox-ha-1-3-20200718-192639-kff7-m-0.c.cloud-dataproc-ci.internal:8443/gateway/example-hive-pii/webhdfs/v1/?op=LISTSTATUS'
+ grep '200 OK'
+ tee test_output
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

curl: (60) SSL certificate problem: EE certificate key too weak
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
+ cat test_output
+ for _ in {1..10}
+ sleep 15s
+ curl -i --cacert /usr/lib/knox/data/security/keystores/gateway-identity.pem -u guest:guest-password -X GET 'https://test-knox-ha-1-3-20200718-192639-kff7-m-0.c.cloud-dataproc-ci.internal:8443/gateway/example-hive-pii/webhdfs/v1/?op=LISTSTATUS'
+ grep '200 OK'
+ tee test_output
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

curl: (60) SSL certificate problem: EE certificate key too weak
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
+ cat test_output
+ for _ in {1..10}
+ sleep 15s
+ curl -i --cacert /usr/lib/knox/data/security/keystores/gateway-identity.pem -u guest:guest-password -X GET 'https://test-knox-ha-1-3-20200718-192639-kff7-m-0.c.cloud-dataproc-ci.internal:8443/gateway/example-hive-pii/webhdfs/v1/?op=LISTSTATUS'
+ grep '200 OK'
+ tee test_output
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

curl: (60) SSL certificate problem: EE certificate key too weak
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
+ cat test_output
+ for _ in {1..10}
+ sleep 15s
+ curl -i --cacert /usr/lib/knox/data/security/keystores/gateway-identity.pem -u guest:guest-password -X GET 'https://test-knox-ha-1-3-20200718-192639-kff7-m-0.c.cloud-dataproc-ci.internal:8443/gateway/example-hive-pii/webhdfs/v1/?op=LISTSTATUS'
+ grep '200 OK'
+ tee test_output
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

curl: (60) SSL certificate problem: EE certificate key too weak
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
+ cat test_output
+ for _ in {1..10}
+ sleep 15s
+ curl -i --cacert /usr/lib/knox/data/security/keystores/gateway-identity.pem -u guest:guest-password -X GET 'https://test-knox-ha-1-3-20200718-192639-kff7-m-0.c.cloud-dataproc-ci.internal:8443/gateway/example-hive-pii/webhdfs/v1/?op=LISTSTATUS'
+ grep '200 OK'
+ tee test_output
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

curl: (60) SSL certificate problem: EE certificate key too weak
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
+ cat test_output
+ return 1
+ [[ 1 == 1 ]]
+ exit 1


----------------------------------------------------------------------
Ran 1 test in 354.833s

FAILED (failures=1)
```

Maybe we need to generate stronger certificate in the Knox initialization action?

**Comment by yunus** [comment]
> Please address [#780 (comment)](https://github.com/GoogleCloudDataproc/initialization-actions/pull/780#issuecomment-660540014)

The Knox's own cli creates certificates with weak keys and there is no parameterisation to choose better keys. I will try to replace it with a custom openssl certificate creation.

**Comment by medb** [comment]
Maybe this is a test issues, and it's possible to configure curl to accept weak cert?

**Comment by yunus** [comment]
> Maybe this is a test issues, and it's possible to configure curl to accept weak cert?

I'll consider that as well. That's an option as long as I don't create a security problem.

As far as I see Debian 10 increased the recommended [security level to 2 from 1](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=907518#20). That's why we are getting the error. I want to understand more what these levels mean before forcing curl/openssl to accept weak keys.

**Comment by yunus** [comment]
@medb can you re-run the test? 
I have tested with latest 1.5 image and it works fine. I see that now Knox 1.3 is installed which uses 2048 bit keys instead of 1024 in older versions. Maybe when we first tested the 1.5 image, Knox was still version 1.1.

**Comment by medb** [comment]
Yes, 1.5 image now passes, but presubmit still fails because tests are failing on 1.3 and 1.4 images that were migrated to Debian 10 already too.

**Comment by medb** [comment]
I will merge this PR because it fixes installation on Debian 10 images, even though tests are failing. Feel free to send fllow up PR for test failures in 1.3 and 1.4 images.

**Review by medb — APPROVED** [review]

**Pull request merged**
