### PR TITLE
[rapids] Update Spark RAPIDS to 22.12

### PR DESCRIPTION
**Pull request by nvliyuan**
Signed-off-by: liyuan <yuali@nvidia.com>
update for spark-rapids v2212 release

### CODE REVIEW

**Comment by nvliyuan** [comment]
verified. @cjac could you help build?

**Comment by nvliyuan** [comment]
@sameerz @mengdong FYI

**Review by cjac — APPROVED** [review]
version changes and removal of XGBOOST_GPU_SUB_VERSION outside of the context of spark != 3

**Comment by nvliyuan** [comment]
> version changes and removal of XGBOOST_GPU_SUB_VERSION outside of the context of spark != 3

yes, could you help merge the pr?

**Pull request merged**
